Repository dropwizard/dropwizard, pull requests merged in 2018-09, with the labels that each got.

#2463 Fix new jersey 2.27 warnings
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/DropwizardResourceConfigTest.java
Labels: bug

#2487 Documenting how to escape periods
  docs/source/manual/core.rst
Labels: documentation

#2490 Update to jetty 9.4.12
  docs/source/manual/configuration.rst
  dropwizard-bom/pom.xml
  dropwizard-core/src/test/resources/yaml/server.yml
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpConnectorFactory.java
  dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpConnectorFactoryTest.java
  dropwizard-jetty/src/test/resources/yaml/http-connector.yml
Labels: improvement

#2501 Support configuration of exception details with JSON logging
  docs/source/manual/configuration.rst
  dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/EventJsonLayoutBaseFactory.java
  dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/layout/ExceptionFormat.java
  dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/EventJsonLayoutBaseFactoryTest.java
  dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/LayoutIntegrationTests.java
  dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/layout/ExceptionFormatTest.java
  dropwizard-json-logging/src/test/resources/yaml/json-log.yml
Labels: improvement

#2506 Convert to lazy evaluation for json event creation
  dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/layout/AccessJsonLayout.java
  dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/layout/EventJsonLayout.java
  dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/layout/MapBuilder.java
  dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/layout/MapBuilderTest.java
Labels: improvement

#2508 Remove openjdk9 and openjdk10 from Travis
  .travis.yml
Labels: improvement

#2509 Add support for pathQuery json access log attribute
  docs/source/manual/configuration.rst
  dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/AccessAttribute.java
  dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/layout/AccessJsonLayout.java
  dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/LayoutIntegrationTests.java
  dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/layout/AccessJsonLayoutTest.java
  dropwizard-json-logging/src/test/resources/yaml/json-access-log.yml
Labels: improvement
