Repository dropwizard/dropwizard, pull requests merged in 2018-03, with the labels that each got.

#2288 Add support for PATCH request to Jersey test client
  dropwizard-testing/src/main/java/io/dropwizard/testing/junit/DropwizardAppRule.java
  dropwizard-testing/src/main/java/io/dropwizard/testing/junit5/DropwizardAppExtension.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/app/DropwizardTestApplication.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/DropwizardAppExtensionTest.java
Labels: improvement

#2290 Fixed template broken after enabling html escaping of strings in Free…
  dropwizard-example/src/main/resources/com/example/helloworld/views/freemarker/person.ftl
  dropwizard-example/src/test/java/com/example/helloworld/IntegrationTest.java
Labels: bug

#2293 Add configuration option to EventJsonLayoutBaseFactory to flatten MDC
  dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/EventJsonLayoutBaseFactory.java
  dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/layout/EventJsonLayout.java
  dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/LayoutIntegrationTests.java
  dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/layout/EventJsonLayoutTest.java
  dropwizard-json-logging/src/test/resources/yaml/json-log.yml
Labels: improvement

#2291 Add a TCP and UDP log appenders to Dropwizard
  docs/source/about/release-notes.rst
  docs/source/manual/configuration.rst
  dropwizard-logging/src/main/java/ch/qos/logback/core/recovery/ResilentSocketOutputStream.java
  dropwizard-logging/src/main/java/io/dropwizard/logging/AbstractOutputStreamAppenderFactory.java
  dropwizard-logging/src/main/java/io/dropwizard/logging/ConsoleAppenderFactory.java
  dropwizard-logging/src/main/java/io/dropwizard/logging/FileAppenderFactory.java
  dropwizard-logging/src/main/java/io/dropwizard/logging/TcpSocketAppenderFactory.java
  dropwizard-logging/src/main/java/io/dropwizard/logging/UdpSocketAppenderFactory.java
  dropwizard-logging/src/main/java/io/dropwizard/logging/socket/DropwizardSocketAppender.java
  dropwizard-logging/src/main/java/io/dropwizard/logging/socket/DropwizardUdpSocketAppender.java
  dropwizard-logging/src/main/resources/META-INF/services/io.dropwizard.logging.AppenderFactory
  dropwizard-logging/src/test/java/ch/qos/logback/core/recovery/ResilentSocketOutputStreamTest.java
  dropwizard-logging/src/test/java/io/dropwizard/logging/TcpSocketAppenderFactoryTest.java
  dropwizard-logging/src/test/java/io/dropwizard/logging/UdpSocketAppenderFactoryTest.java
  dropwizard-logging/src/test/java/io/dropwizard/logging/socket/DropwizardUdpSocketAppenderTest.java
  dropwizard-logging/src/test/resources/yaml/logging-tcp-buffered.yml
  dropwizard-logging/src/test/resources/yaml/logging-tcp-custom.yml
  dropwizard-logging/src/test/resources/yaml/logging-tcp.yml
  dropwizard-logging/src/test/resources/yaml/logging-udp.yml
Labels: feature

#2304 Allow lazy initialization of resources in ResourceTestRule
  docs/source/about/release-notes.rst
  dropwizard-testing/pom.xml
  dropwizard-testing/src/main/java/io/dropwizard/testing/common/DropwizardTestResourceConfig.java
  dropwizard-testing/src/main/java/io/dropwizard/testing/common/Resource.java
  dropwizard-testing/src/main/java/io/dropwizard/testing/common/ResourceTestJerseyConfiguration.java
  dropwizard-testing/src/main/java/io/dropwizard/testing/junit/MockitoTestRule.java
  dropwizard-testing/src/main/java/io/dropwizard/testing/junit/ResourceTestRule.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/app/PersonResourceTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/app/ResourceTestRuleTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/app/ResourceTestRuleWithGrizzlyTest.java
Labels: feature

#2310 Remove metrics-ganglia completely
  docs/source/about/javadoc.rst
  docs/source/manual/configuration.rst
  dropwizard-bom/pom.xml
Labels: documentation

#2315 Switch the build to run on JDK 10 from JDK 9
  .travis.yml
  dropwizard-example/pom.xml
  dropwizard-http2/pom.xml
  dropwizard-testing/pom.xml
  pom.xml
Labels: improvement

#2316 Remove expected exceptions from tests
  dropwizard-auth/src/test/java/io/dropwizard/auth/CachingAuthenticatorTest.java
  dropwizard-client/src/test/java/io/dropwizard/client/proxy/HttpClientConfigurationTest.java
  dropwizard-configuration/src/test/java/io/dropwizard/configuration/BaseConfigurationFactoryTest.java
  dropwizard-configuration/src/test/java/io/dropwizard/configuration/ConfigurationFactoryFactoryTest.java
  dropwizard-configuration/src/test/java/io/dropwizard/configuration/EnvironmentVariableLookupTest.java
  dropwizard-configuration/src/test/java/io/dropwizard/configuration/EnvironmentVariableSubstitutorTest.java
  dropwizard-db/src/test/java/io/dropwizard/db/DataSourceFactoryTest.java
  dropwizard-example/src/test/java/com/example/helloworld/db/PersonDAOTest.java
  dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/AbstractDAOTest.java
  dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/UnitOfWorkAwareProxyFactoryTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/guava/OptionalCookieParamResourceTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/guava/OptionalHeaderParamResourceTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/guava/OptionalQueryParamResourceTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalCookieParamResourceTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalHeaderParamResourceTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalQueryParamResourceTest.java
  dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpsConnectorFactoryTest.java
  dropwizard-servlets/src/test/java/io/dropwizard/servlets/tasks/PostBodyTaskTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/FixtureHelpersTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DAOTestRuleTest.java
  dropwizard-util/src/test/java/io/dropwizard/util/DurationTest.java
  dropwizard-util/src/test/java/io/dropwizard/util/GenericsTest.java
  dropwizard-util/src/test/java/io/dropwizard/util/SizeTest.java
Labels: improvement
