Repository dropwizard/dropwizard, pull requests merged in 2018-04, with the labels that each got.

#2325 Upgrade Liquibase from 3.5.5 to 3.6.0, to be compatible with Jdk10.
  dropwizard-bom/pom.xml
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/AbstractMigrationTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbCalculateChecksumCommandTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbDumpCommandTest.java
  dropwizard-migrations/src/test/resources/test-db.mv.db
Labels: improvement

#2328 Documentation/Sphinx updates
  docs/.gitignore
  docs/Guardfile
  docs/Makefile
  docs/README.md
  docs/list_contributors.rb
  docs/requirements.txt
  docs/source/about/contributors.rst
  docs/source/about/javadoc.rst
  docs/source/conf.py
Labels: documentation, improvement

#2330 Upgrade sphinx-maven-plugin
  docs/pom.xml
  docs/requirements.txt
  pom.xml
Labels: documentation
