Repository dropwizard/dropwizard, pull requests merged in 2018-06, with the labels that each got.

#2382 UUID param to length check input
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/UUIDParam.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/UUIDParamTest.java
Labels: bug

#2389 Overhaul logging resource endpoints
  dropwizard-benchmarks/pom.xml
  dropwizard-benchmarks/src/main/java/io/dropwizard/benchmarks/jersey/DropwizardResourceConfigBenchmark.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/DropwizardResourceConfigTest.java
Labels: improvement

#2384 Throttling logging appender
  dropwizard-logging/src/main/java/io/dropwizard/logging/AbstractAppenderFactory.java
  dropwizard-logging/src/main/java/io/dropwizard/logging/AsyncAppenderBaseProxy.java
  dropwizard-logging/src/main/java/io/dropwizard/logging/DefaultLoggingFactory.java
  dropwizard-logging/src/main/java/io/dropwizard/logging/ThrottlingAppenderWrapper.java
  dropwizard-logging/src/test/java/io/dropwizard/logging/ThrottlingAppenderTest.java
  dropwizard-logging/src/test/resources/yaml/appender_with_invalid_message_rate.yml
  dropwizard-logging/src/test/resources/yaml/appender_with_zero_message_rate.yml
  dropwizard-logging/src/test/resources/yaml/logging-message-rate.yml
Labels: feature

#2404 Clean up tests in jersey.params
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/BooleanParamTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/DateTimeParamTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/DurationParamTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/InstantParamTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/IntParamTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/LocalDateParamTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/LongParamTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/NonEmptyStringParamTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/SizeParamTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/UUIDParamTest.java
Labels: improvement

#2405 Overhaul https logging of supported protocols and cipher suites
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpsConnectorFactory.java
  dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpsConnectorFactoryTest.java
Labels: feature

#2395 Update to Jersey 2.27
  dropwizard-auth/src/main/java/io/dropwizard/auth/AuthValueFactoryProvider.java
  dropwizard-auth/src/main/java/io/dropwizard/auth/OptionalPrincipalContainerRequestValueFactory.java
  dropwizard-auth/src/main/java/io/dropwizard/auth/PolymorphicAuthValueFactoryProvider.java
  dropwizard-auth/src/main/java/io/dropwizard/auth/PrincipalContainerRequestValueFactory.java
  dropwizard-bom/pom.xml
  dropwizard-client/pom.xml
  dropwizard-client/src/main/java/io/dropwizard/client/JerseyClientBuilder.java
  dropwizard-client/src/test/java/io/dropwizard/client/JerseyClientBuilderTest.java
  dropwizard-client/src/test/java/io/dropwizard/client/JerseyClientIntegrationTest.java
  dropwizard-core/src/main/java/io/dropwizard/server/AbstractServerFactory.java
  dropwizard-e2e/src/main/java/com/example/app1/App1.java
  dropwizard-e2e/src/main/java/com/example/app1/CustomJsonProvider.java
  dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/JerseyIntegrationTest.java
  dropwizard-jersey/pom.xml
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/guava/OptionalParamBinder.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/guava/OptionalParamConverterProvider.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/guava/OptionalParamFeature.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/jackson/JacksonBinder.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/jackson/JacksonFeature.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalParamBinder.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalParamConverterProvider.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalParamFeature.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/sessions/FlashFactory.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/sessions/HttpSessionFactory.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/sessions/SessionFactoryProvider.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/HibernateValidationBinder.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/HibernateValidationFeature.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ConstraintViolationExceptionMapperTest.java
  dropwizard-testing/src/main/java/io/dropwizard/testing/common/DropwizardTestResourceConfig.java
  dropwizard-testing/src/main/java/io/dropwizard/testing/junit/DropwizardAppRule.java
  dropwizard-testing/src/main/java/io/dropwizard/testing/junit5/DropwizardAppExtension.java
  suppressed-cves.xml
Labels: improvement

#2407 Logging throttle tests now CI friendly
  dropwizard-logging/src/test/java/io/dropwizard/logging/ThrottlingAppenderTest.java
  dropwizard-logging/src/test/resources/yaml/logging-message-rate.yml
Labels: improvement

#2409 Improve validation message for min/max duration
  dropwizard-logging/src/test/java/io/dropwizard/logging/ThrottlingAppenderTest.java
  dropwizard-validation/src/main/java/io/dropwizard/validation/MaxDuration.java
  dropwizard-validation/src/main/java/io/dropwizard/validation/MinDuration.java
  dropwizard-validation/src/test/java/io/dropwizard/validation/DurationValidatorTest.java
Labels: improvement

#2414 Document that the Timed and Metered can't be used at the same time.
  docs/source/manual/core.rst
Labels: documentation

#2413 Simplify SelfValidatingValidator
  dropwizard-validation/src/main/java/io/dropwizard/validation/selfvalidating/SelfValidatingValidator.java
  dropwizard-validation/src/test/java/io/dropwizard/validation/selfvalidating/SelfValidatingValidatorTest.java
Labels: improvement

#2417 Disable protocols less secure than tls v1.2 by default
  docs/source/manual/configuration.rst
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpsConnectorFactory.java
Labels: security
