Repository dropwizard/dropwizard, pull requests merged in 2018-10, with the labels that each got.

#2511 Add safe Jackson deserializers to prevent a DoS attack
  dropwizard-jackson/src/main/java/io/dropwizard/jackson/Jackson.java
  dropwizard-jackson/src/main/java/io/dropwizard/jackson/SafeDurationDeserializer.java
  dropwizard-jackson/src/main/java/io/dropwizard/jackson/SafeInstantDeserializer.java
  dropwizard-jackson/src/main/java/io/dropwizard/jackson/SafeJavaTimeModule.java
  dropwizard-jackson/src/test/java/io/dropwizard/jackson/JacksonDeserializationOfBigNumbersToDurationTest.java
  dropwizard-jackson/src/test/java/io/dropwizard/jackson/JacksonDeserializationOfBigNumbersToInstantTest.java
Labels: bug, security

#2514 Remove redundant "the"
  docs/source/manual/client.rst
  docs/source/manual/internals.rst
Labels: documentation

#2526 Fix issue #2500 Include default requestLog format string in documentation
  docs/source/manual/configuration.rst
Labels: documentation

#2522 Enable validator injection by default #2
  dropwizard-core/src/main/java/io/dropwizard/cli/EnvironmentCommand.java
  dropwizard-core/src/main/java/io/dropwizard/setup/Environment.java
  dropwizard-core/src/main/java/io/dropwizard/validation/GetResourceContextFeature.java
  dropwizard-core/src/main/java/io/dropwizard/validation/InjectValidatorBundle.java
  dropwizard-core/src/main/java/io/dropwizard/validation/InjectValidatorFeature.java
  dropwizard-core/src/test/java/io/dropwizard/validation/InjectValidatorFeatureTest.java
  dropwizard-e2e/src/main/java/com/example/validation/InjectValidatorApp.java
  dropwizard-e2e/src/test/java/com/example/validation/InjectValidatorBundleTest.java
  dropwizard-e2e/src/test/java/com/example/validation/InjectValidatorTest.java
Labels: improvement

#2529 We're using OpenJDK now
  .travis_after_success.sh
Labels: bug

#2537 Upgrade dependencies
  dropwizard-bom/pom.xml
  dropwizard-example/pom.xml
  dropwizard-http2/pom.xml
  dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/setup/ExecutorServiceBuilder.java
  dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/setup/ScheduledExecutorServiceBuilder.java
  dropwizard-testing/pom.xml
  pom.xml
Labels: improvement
