Repository dropwizard/dropwizard, pull requests merged in 2018-02, with the labels that each got.

#2266 Upgrade handling an unknown value in FuzzyEnumModule
  dropwizard-jackson/src/main/java/io/dropwizard/jackson/FuzzyEnumModule.java
  dropwizard-jackson/src/test/java/io/dropwizard/jackson/FuzzyEnumModuleTest.java
Labels: bug

#2267 Remove usage of the deprecated Guava Files API
  dropwizard-e2e/src/test/java/com/example/badlog/BadLogTest.java
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/NetUtil.java
Labels: improvement

#2271 Strip the Content-Length header after decompressing HTTP requests
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/BiDiGzipHandler.java
  dropwizard-jetty/src/test/java/io/dropwizard/jetty/BiDiGzipHandlerTest.java
Labels: bug

#2270 Upgrade Jackson to 2.8.11 in 1.1.* to address a CVE
  dropwizard-bom/pom.xml
Labels: security

#2272 Upgrade Jadira to 7.0.0-rc1
  dropwizard-bom/pom.xml
  dropwizard-hibernate/pom.xml
  dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/JerseyIntegrationTest.java
  dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/SessionFactoryFactoryTest.java
  pom.xml
Labels: improvement

#2273 Deprecate the native Hibernate criteria API in AbstractDAO
  dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/AbstractDAO.java
  dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/AbstractDAOTest.java
Labels: improvement

#2277 Make sure test Jersey test client uses Dropwizard's ObjectMapper
  dropwizard-testing/src/main/java/io/dropwizard/testing/junit/DropwizardAppRule.java
  dropwizard-testing/src/main/java/io/dropwizard/testing/junit5/DropwizardAppExtension.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/app/DropwizardTestApplication.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/DropwizardAppExtensionTest.java
Labels: bug

#2278 Run code coverage only if needed
  .travis.yml
  pom.xml
Labels: improvement

#2279 Correctly handle the default context path when logging endpoints
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java
Labels: improvement

#2283 Update release notes
  docs/source/about/release-notes.rst
Labels: documentation

#2286 Migrate to Circle CI 2.0
  .circleci/config.yml
  circle.yml
Labels: improvement
