Repository dropwizard/dropwizard, pull requests merged in 2018-07, with the labels that each got.

#2403 Add more Java versions to Travis CI build matrix
  .travis.yml
  dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/pom.xml
  dropwizard-bom/pom.xml
  dropwizard-example/pom.xml
  dropwizard-http2/pom.xml
  dropwizard-jersey/pom.xml
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbMigrateDifferentFileCommandTest.java
  pom.xml
Labels: improvement

#2375 Support expirable log level configurations
  docs/source/manual/core.rst
  dropwizard-servlets/src/main/java/io/dropwizard/servlets/tasks/LogConfigurationTask.java
  dropwizard-servlets/src/test/java/io/dropwizard/servlets/tasks/LogConfigurationTaskTest.java
Labels: feature

#2430 Fix incorrect reading of somaxconn for tcp backlog on linux
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/NetUtil.java
  dropwizard-jetty/src/test/java/io/dropwizard/jetty/NetUtilTest.java
Labels: bug

#2444 Replace remaining use of Hamcrest with AssertJ
  dropwizard-auth/src/test/java/io/dropwizard/auth/CachingAuthenticatorTest.java
  dropwizard-bom/pom.xml
  dropwizard-client/src/test/java/io/dropwizard/client/DropwizardApacheConnectorTest.java
  dropwizard-configuration/src/test/java/io/dropwizard/configuration/ConfigurationValidationExceptionTest.java
  dropwizard-configuration/src/test/java/io/dropwizard/configuration/EnvironmentVariableLookupTest.java
  dropwizard-configuration/src/test/java/io/dropwizard/configuration/EnvironmentVariableSubstitutorTest.java
  dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/DBIHealthCheckTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/gzip/ConfiguredGZipEncoderTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/jackson/JacksonMessageBodyProviderTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ConstraintViolationExceptionMapperTest.java
  dropwizard-jetty/src/test/java/io/dropwizard/jetty/NetUtilTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/DropwizardTestSupportTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleConfigOverrideTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/DropwizardAppExtensionTest.java
  dropwizard-validation/src/test/java/io/dropwizard/validation/PortRangeValidatorTest.java
  pom.xml
Labels: improvement

#2448 Ensure DropwizardResourceConfig#forTesting() is using a random port
  dropwizard-auth/src/test/java/io/dropwizard/auth/AbstractAuthResourceConfig.java
  dropwizard-auth/src/test/java/io/dropwizard/auth/chained/ChainedAuthProviderTest.java
  dropwizard-benchmarks/src/main/java/io/dropwizard/benchmarks/jersey/DropwizardResourceConfigBenchmark.java
  dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/JerseyIntegrationTest.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/AsyncServletTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/DropwizardResourceConfigTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/JerseyContentTypeTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/caching/CacheControlledResponseFeatureTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/errors/ErrorEntityWriterTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/errors/LoggingExceptionMapperTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/filter/AllowedMethodsFilterTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/guava/OptionalCookieParamResourceTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/guava/OptionalFormParamResourceTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/guava/OptionalHeaderParamResourceTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/guava/OptionalMessageBodyWriterTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/guava/OptionalQueryParamResourceTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/jackson/JsonProcessingExceptionMapperTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalCookieParamResourceTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalDoubleMessageBodyWriterTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalFormParamResourceTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalHeaderParamResourceTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalIntMessageBodyWriterTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalLongMessageBodyWriterTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalMessageBodyWriterTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalQueryParamResourceTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/NonEmptyStringParamProviderTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/sessions/FlashFactoryTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/sessions/HttpSessionFactoryTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ConstraintViolationExceptionMapperTest.java
  dropwizard-testing/src/main/java/io/dropwizard/testing/common/DropwizardTestResourceConfig.java
  dropwizard-views-freemarker/src/test/java/io/dropwizard/views/freemarker/MultipleContentTypeTest.java
  dropwizard-views-mustache/src/test/java/io/dropwizard/views/mustache/MustacheViewRendererFileSystemTest.java
  dropwizard-views-mustache/src/test/java/io/dropwizard/views/mustache/MustacheViewRendererTest.java
Labels: improvement

#2449 Upgrade to Maven Compiler plugin 3.8.0
  dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/pom.xml
  dropwizard-example/pom.xml
  pom.xml
Labels: improvement
