Repository dropwizard/dropwizard, pull requests merged in 2019-04, with the labels that each got.

#2720 DropwizardTestSupport should only override the app's ConfigurationSou…
  dropwizard-testing/src/main/java/io/dropwizard/testing/DropwizardTestSupport.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/DropwizardTestSupportWithResourceConfigProviderTest.java
Labels: bug

#2722 Allow to disable logging bootstrap in DAOTest
  dropwizard-testing/src/main/java/io/dropwizard/testing/common/DAOTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/app/ResourceTestRuleWithoutLoggingBootstrapTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DAOTestRuleWithoutLoggingBootstrapTest.java
Labels: improvement

#2723 Use ReadTheDocs theme for documentation
  docs/Makefile
  docs/requirements.txt
  docs/source/_static/dropwizard-logo.svg
  docs/source/_static/dropwizard.css
  docs/source/_themes/dropwizard/genindex.html
  docs/source/_themes/dropwizard/layout.html
  docs/source/_themes/dropwizard/less/accordion.less
  docs/source/_themes/dropwizard/less/alerts.less
  docs/source/_themes/dropwizard/less/bootstrap.less
  docs/source/_themes/dropwizard/less/breadcrumbs.less
  docs/source/_themes/dropwizard/less/button-groups.less
  docs/source/_themes/dropwizard/less/buttons.less
  docs/source/_themes/dropwizard/less/carousel.less
  docs/source/_themes/dropwizard/less/close.less
  docs/source/_themes/dropwizard/less/code.less
  docs/source/_themes/dropwizard/less/component-animations.less
  docs/source/_themes/dropwizard/less/dropdowns.less
  docs/source/_themes/dropwizard/less/dropwizard.less
  docs/source/_themes/dropwizard/less/forms.less
  docs/source/_themes/dropwizard/less/grid.less
  docs/source/_themes/dropwizard/less/hero-unit.less
  docs/source/_themes/dropwizard/less/labels.less
  docs/source/_themes/dropwizard/less/layouts.less
  docs/source/_themes/dropwizard/less/mixins.less
  docs/source/_themes/dropwizard/less/modals.less
  docs/source/_themes/dropwizard/less/navbar.less
  docs/source/_themes/dropwizard/less/navs.less
  docs/source/_themes/dropwizard/less/pager.less
  docs/source/_themes/dropwizard/less/pagination.less
  docs/source/_themes/dropwizard/less/patterns.less
  docs/source/_themes/dropwizard/less/popovers.less
  docs/source/_themes/dropwizard/less/print.less
  docs/source/_themes/dropwizard/less/progress-bars.less
  docs/source/_themes/dropwizard/less/reset.less
  docs/source/_themes/dropwizard/less/responsive.less
  docs/source/_themes/dropwizard/less/scaffolding.less
  docs/source/_themes/dropwizard/less/sprites.less
  docs/source/_themes/dropwizard/less/tables.less
  docs/source/_themes/dropwizard/less/thumbnails.less
  docs/source/_themes/dropwizard/less/tooltip.less
  docs/source/_themes/dropwizard/less/type.less
  docs/source/_themes/dropwizard/less/utilities.less
  docs/source/_themes/dropwizard/less/variables.less
  docs/source/_themes/dropwizard/less/wells.less
  docs/source/_themes/dropwizard/page.html
  docs/source/_themes/dropwizard/search.html
  docs/source/_themes/dropwizard/static/dropwizard.css
  docs/source/_themes/dropwizard/theme.conf
  docs/source/about/index.rst
  docs/source/about/todos.rst
  docs/source/conf.py
  docs/source/dropwizard-logo.png
  docs/source/dropwizard-logo.svg
  docs/source/index.rst
Labels: documentation

#2743 Support configuration of jetty dump properties
  docs/source/manual/configuration.rst
  dropwizard-core/src/main/java/io/dropwizard/server/AbstractServerFactory.java
  dropwizard-core/src/test/java/io/dropwizard/server/DefaultServerFactoryTest.java
Labels: improvement

#2741 Allow response content type to be specified for a Task
  dropwizard-servlets/src/main/java/io/dropwizard/servlets/tasks/PostBodyTask.java
  dropwizard-servlets/src/main/java/io/dropwizard/servlets/tasks/Task.java
  dropwizard-servlets/src/main/java/io/dropwizard/servlets/tasks/TaskServlet.java
  dropwizard-servlets/src/test/java/io/dropwizard/servlets/tasks/TaskServletTest.java
Labels: improvement

#2748 Don't use X-Forwarded-* headers by default
  docs/source/about/release-notes.rst
  docs/source/manual/configuration.rst
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpConnectorFactory.java
  dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpConnectorFactoryTest.java
  dropwizard-jetty/src/test/resources/yaml/http-connector.yml
Labels: security
