Repository dropwizard/dropwizard, pull requests merged in 2019-03, with the labels that each got.

#2673 Improve Dropwizard test support
  dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/LazyLoadingTest.java
  dropwizard-testing/src/main/java/io/dropwizard/testing/DropwizardTestSupport.java
  dropwizard-testing/src/main/java/io/dropwizard/testing/junit/DropwizardAppRule.java
  dropwizard-testing/src/main/java/io/dropwizard/testing/junit5/DropwizardAppExtension.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/DropwizardTestSupportTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/DropwizardTestSupportWithMissingConfigurationTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/DropwizardTestSupportWithResourceConfigProviderTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/DropwizardTestSupportWithUrlConfigProviderTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/app/GzipDefaultVaryBehaviourTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/app/PersonResourceExceptionMapperTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/app/ResourceTestRuleTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/app/ResourceTestRuleWithGrizzlyTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/app/ResourceTestRuleWithoutLoggingBootstrap.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleConfigOverrideTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleReentrantTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleResetConfigOverrideTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleWithExplicitTest.java
Labels: improvement

#2674 Support URL encoded entry names in `ResourceURL#isDirectory()`
  dropwizard-servlets/src/main/java/io/dropwizard/servlets/assets/ResourceURL.java
  dropwizard-servlets/src/test/java/io/dropwizard/servlets/assets/ResourceURLTest.java
  dropwizard-servlets/src/test/resources/resources.jar
Labels: bug

#2675 Add documentation for metrics annotations
  docs/source/manual/core.rst
Labels: documentation

#2683 Fixed flaky test in CachingAuthorizer
  dropwizard-auth/src/main/java/io/dropwizard/auth/CachingAuthorizer.java
  dropwizard-auth/src/test/java/io/dropwizard/auth/CachingAuthorizerTest.java
Labels: improvement

#2682 Update JdbiFactory to use metrics' InstrumentedSqlLogger
  dropwizard-jdbi3/src/main/java/io/dropwizard/jdbi3/JdbiFactory.java
  dropwizard-jdbi3/src/test/java/io/dropwizard/jdbi3/JdbiFactoryTest.java
Labels: improvement

#2684 Document asynchronous logging
  docs/source/manual/configuration.rst
  docs/source/manual/core.rst
Labels: documentation

#2687 Move upgrade notes from GitHub wiki into documentation
  docs/source/manual/index.rst
  docs/source/manual/upgrade-notes.rst
  docs/source/manual/upgrade-notes/upgrade-notes-0_7_x.rst
  docs/source/manual/upgrade-notes/upgrade-notes-0_8_x.rst
  docs/source/manual/upgrade-notes/upgrade-notes-0_9_x.rst
  docs/source/manual/upgrade-notes/upgrade-notes-1_0_x.rst
  docs/source/manual/upgrade-notes/upgrade-notes-1_1_x.rst
  docs/source/manual/upgrade-notes/upgrade-notes-2_0_x.rst
Labels: documentation

#2692 Add documentation about import changes for HK2
  docs/source/manual/upgrade-notes/upgrade-notes-2_0_x.rst
Labels: documentation

#2667 Verify dependency signatures during build
  pom.xml
Labels: security

#2686 Add data size class adhering to the correct SI and IEC prefixes
  docs/source/manual/configuration.rst
  dropwizard-benchmarks/src/main/java/io/dropwizard/benchmarks/util/DataSizeBenchmark.java
  dropwizard-example/example.yml
  dropwizard-example/src/test/resources/test-example.yml
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/GzipHandlerFactory.java
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpConnectorFactory.java
  dropwizard-jetty/src/test/java/io/dropwizard/jetty/GzipHandlerFactoryTest.java
  dropwizard-jetty/src/test/java/io/dropwizard/jetty/GzipHandlerTest.java
  dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpConnectorFactoryTest.java
  dropwizard-jetty/src/test/resources/yaml/gzip.yml
  dropwizard-logging/src/main/java/io/dropwizard/logging/FileAppenderFactory.java
  dropwizard-logging/src/main/java/io/dropwizard/logging/TcpSocketAppenderFactory.java
  dropwizard-logging/src/test/java/io/dropwizard/logging/DefaultLoggingFactoryTest.java
  dropwizard-logging/src/test/java/io/dropwizard/logging/FileAppenderFactoryTest.java
  dropwizard-logging/src/test/java/io/dropwizard/logging/TcpSocketAppenderFactoryTest.java
  dropwizard-logging/src/test/resources/yaml/appender_file_cap.yaml
  dropwizard-logging/src/test/resources/yaml/appender_file_cap2.yaml
  dropwizard-logging/src/test/resources/yaml/appender_file_cap_invalid.yaml
  dropwizard-logging/src/test/resources/yaml/logging-tcp-buffered.yml
  dropwizard-logging/src/test/resources/yaml/logging-tcp-custom.yml
  dropwizard-logging/src/test/resources/yaml/logging.yml
  dropwizard-logging/src/test/resources/yaml/logging_advanced.yml
  dropwizard-util/pom.xml
  dropwizard-util/src/main/java/io/dropwizard/util/DataSize.java
  dropwizard-util/src/main/java/io/dropwizard/util/DataSizeUnit.java
  dropwizard-util/src/main/java/io/dropwizard/util/Size.java
  dropwizard-util/src/main/java/io/dropwizard/util/SizeUnit.java
  dropwizard-util/src/test/java/io/dropwizard/util/DataSizeTest.java
  dropwizard-util/src/test/java/io/dropwizard/util/DataSizeUnitTest.java
  dropwizard-util/src/test/java/io/dropwizard/util/SizeTest.java
  dropwizard-util/src/test/java/io/dropwizard/util/SizeUnitTest.java
  dropwizard-validation/src/main/java/io/dropwizard/validation/DataSizeRange.java
  dropwizard-validation/src/main/java/io/dropwizard/validation/MaxDataSize.java
  dropwizard-validation/src/main/java/io/dropwizard/validation/MaxDataSizeValidator.java
  dropwizard-validation/src/main/java/io/dropwizard/validation/MinDataSize.java
  dropwizard-validation/src/main/java/io/dropwizard/validation/MinDataSizeValidator.java
  dropwizard-validation/src/test/java/io/dropwizard/validation/DataSizeValidatorTest.java
Labels: documentation, feature

#2701 Add some additional information in the 2.0.0 release notes
  docs/source/about/release-notes.rst
Labels: documentation

#2709 Add ProxyConectionFactory for enabling the proxy protocol.
  docs/source/about/release-notes.rst
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpConnectorFactory.java
  dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpConnectorFactoryTest.java
Labels: feature

#2703 #2702 allowing validation query to be null
  dropwizard-db/src/main/java/io/dropwizard/db/DataSourceFactory.java
  dropwizard-db/src/main/java/io/dropwizard/db/PooledDataSourceFactory.java
  dropwizard-db/src/test/java/io/dropwizard/db/DataSourceConfigurationTest.java
  dropwizard-db/src/test/java/io/dropwizard/db/DataSourceFactoryTest.java
  dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/SessionFactoryHealthCheck.java
  dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/HibernateBundleTest.java
  dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/SessionFactoryHealthCheckTest.java
  dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/DBIFactory.java
  dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/DBIHealthCheck.java
  dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/DBIHealthCheckTest.java
  dropwizard-jdbi3/src/main/java/io/dropwizard/jdbi3/JdbiFactory.java
  dropwizard-jdbi3/src/main/java/io/dropwizard/jdbi3/JdbiHealthCheck.java
  dropwizard-jdbi3/src/test/java/io/dropwizard/jdbi3/JdbiFactoryTest.java
  dropwizard-jdbi3/src/test/java/io/dropwizard/jdbi3/JdbiHealthCheckTest.java
Labels: improvement

#2711 Retrieve Connector Information in ServiceLifecycleListener
  docs/source/about/release-notes.rst
  dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/PortDescriptor.java
  dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/ServerLifecycleListener.java
  dropwizard-lifecycle/src/test/java/io/dropwizard/lifecycle/ServerLifecycleListenerTest.java
Labels: feature
