Repository dropwizard/dropwizard, pull requests merged in 2019-08, with the labels that each got.

#2869 Slight message change
  dropwizard-configuration/src/main/java/io/dropwizard/configuration/BaseConfigurationFactory.java
  dropwizard-configuration/src/test/java/io/dropwizard/configuration/BaseConfigurationFactoryTest.java
Labels: improvement

#2870 Upgrade to Jackson 2.9.9.20190807
  dropwizard-bom/pom.xml
Labels: security

#2871 Upgrade to Jackson 2.9.9.20190807
  dropwizard-bom/pom.xml
Labels: security

#2874 Updating configuration testing documentation
  docs/source/manual/testing.rst
Labels: documentation

#2889 fixed typo
  docs/source/manual/internals.rst
Labels: documentation
