Repository dropwizard/dropwizard, pull requests merged in 2019-02, with the labels that each got.

#2628 Update dependencies to latest patch-level
  dropwizard-bom/pom.xml
  pom.xml
Labels: dependencies

#2637 Deprecate *Param classes, will be removed in 3.0.0
  docs/source/about/release-notes.rst
  docs/source/manual/core.rst
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/BooleanParam.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/DateTimeParam.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/DurationParam.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/InstantParam.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/IntParam.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/LocalDateParam.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/LongParam.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/SizeParam.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/UUIDParam.java
Labels: documentation, improvement

#2643 Test support cleanup on before exceptions
  dropwizard-e2e/src/test/java/com/example/badlog/BadLogTest.java
  dropwizard-testing/src/main/java/io/dropwizard/testing/DropwizardTestSupport.java
Labels: bug

#2649 Use instrumented thread factory
  docs/source/manual/core.rst
  dropwizard-client/src/test/java/io/dropwizard/client/JerseyClientBuilderTest.java
  dropwizard-core/src/main/java/io/dropwizard/setup/Environment.java
  dropwizard-lifecycle/pom.xml
  dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/setup/ExecutorServiceBuilder.java
  dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/setup/LifecycleEnvironment.java
  dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/setup/ScheduledExecutorServiceBuilder.java
  dropwizard-lifecycle/src/test/java/io/dropwizard/lifecycle/setup/ExecutorServiceBuilderTest.java
  dropwizard-lifecycle/src/test/java/io/dropwizard/lifecycle/setup/LifecycleEnvironmentTest.java
  dropwizard-lifecycle/src/test/java/io/dropwizard/lifecycle/setup/ScheduledExecutorServiceBuilderTest.java
  dropwizard-metrics/src/test/java/io/dropwizard/metrics/CsvReporterFactoryTest.java
Labels: improvement
