Repository dropwizard/dropwizard, pull requests merged in 2019-06, with the labels that each got.

#2786 Add current class loader to javassist ClassPool
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java
Labels: bug

#2795 Adds a request logging uri filter
  docs/source/about/release-notes.rst
  docs/source/manual/core.rst
  dropwizard-request-logging/src/main/java/io/dropwizard/request/logging/filter/UriFilterFactory.java
  dropwizard-request-logging/src/main/resources/META-INF/services/io.dropwizard.jackson.Discoverable
  dropwizard-request-logging/src/main/resources/META-INF/services/io.dropwizard.logging.filter.FilterFactory
  dropwizard-request-logging/src/test/java/io/dropwizard/request/logging/filter/UriFilterFactoryTest.java
Labels: feature

#2803 Fixed broken link.
  docs/source/getting-started.rst
Labels: documentation

#2804 CachingAuthenticator documentation fix
  dropwizard-auth/src/main/java/io/dropwizard/auth/CachingAuthenticator.java
Labels: documentation

#2801 Default values allowed on strict undefined config env vars
  dropwizard-configuration/src/main/java/io/dropwizard/configuration/EnvironmentVariableLookup.java
  dropwizard-configuration/src/main/java/io/dropwizard/configuration/EnvironmentVariableSubstitutor.java
  dropwizard-configuration/src/test/java/io/dropwizard/configuration/EnvironmentVariableLookupTest.java
  dropwizard-configuration/src/test/java/io/dropwizard/configuration/EnvironmentVariableSubstitutorTest.java
Labels: improvement

#2805 Updates Conscrypt docs to follow recommended usage patterns (#2736)
  docs/source/manual/core.rst
Labels: documentation

#2811 Allow to setNormalizeUri on HTTP client
  dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java
  dropwizard-client/src/main/java/io/dropwizard/client/HttpClientConfiguration.java
  dropwizard-client/src/test/java/io/dropwizard/client/HttpClientBuilderTest.java
Labels: improvement

#2816 Ignore CVE-2019-12814 (Jackson 2.9.9) until a fix is available
  suppressed-cves.xml
Labels: security

#2819 Allow simple logger level config to support "OFF"
  dropwizard-logging/src/main/java/io/dropwizard/logging/DefaultLoggingFactory.java
  dropwizard-logging/src/test/java/io/dropwizard/logging/DefaultLoggingFactoryTest.java
  dropwizard-logging/src/test/resources/yaml/logging_level_off.yml
Labels: improvement

#2812 Add support for configuring Jetty cookie compliance
  .gitignore
  docs/source/about/release-notes.rst
  docs/source/manual/configuration.rst
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpConnectorFactory.java
  dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpConnectorFactoryTest.java
  dropwizard-jetty/src/test/resources/yaml/http-connector.yml
Labels: improvement
