Repository dropwizard/dropwizard, pull requests merged in 2019-07, with the labels that each got.

#2825 Upgrade jackson-databind to 2.9.9.1 (1.3 releases)
  dropwizard-bom/pom.xml
Labels: security

#2836 Remove OWASP dependency check plugin because of false positives
  pom.xml
  suppressed-cves.xml
Labels: security

#2826 Upgrade jackson-databind to 2.9.9.1
  dropwizard-bom/pom.xml
Labels: security

#2829 Use commons-text native undef var detection
  dropwizard-configuration/src/main/java/io/dropwizard/configuration/EnvironmentVariableSubstitutor.java
Labels: improvement

#2839 Add a JSONUnauthorizedHandler
  dropwizard-auth/src/main/java/io/dropwizard/auth/JSONUnauthorizedHandler.java
Labels: feature

#2841 Add a JSONUnauthorizedHandler
  dropwizard-auth/src/main/java/io/dropwizard/auth/JSONUnauthorizedHandler.java
Labels: feature

#2837 Pass request UriInfo to Authorizer.authorize
  docs/source/about/release-notes.rst
  dropwizard-auth/src/main/java/io/dropwizard/auth/AuthFilter.java
  dropwizard-auth/src/main/java/io/dropwizard/auth/Authorizer.java
  dropwizard-auth/src/main/java/io/dropwizard/auth/CachingAuthorizer.java
  dropwizard-auth/src/test/java/io/dropwizard/auth/CachingAuthorizerTest.java
Labels: feature

#2852 Update of 2.0.0 release notes mention of Jersey version
  docs/source/about/docs-index.rst
  docs/source/about/release-notes.rst
Labels: documentation

#2854 Increases the values in the hibernate validator annotations
  dropwizard-core/src/main/java/io/dropwizard/server/AbstractServerFactory.java
  dropwizard-core/src/main/java/io/dropwizard/server/DefaultServerFactory.java
Labels: bug
