Repository dropwizard/dropwizard, pull requests merged in 2020-04, with the labels that each got.

#3227 Upgrade to SnakeYAML to address CVE-2017-18640
  dropwizard-bom/pom.xml
Labels: security

#3228 Upgrade to SnakeYAML to address CVE-2017-18640
  dropwizard-dependencies/pom.xml
Labels: security

#3191 Add CachingAuthenticator option to enable negative caches
  dropwizard-auth/src/main/java/io/dropwizard/auth/CachingAuthenticator.java
  dropwizard-auth/src/test/java/io/dropwizard/auth/CachingAuthenticatorTest.java
Labels: improvement

#2992 Support comments in DiscoverableSubtypeResolver
  dropwizard-jackson/src/main/java/io/dropwizard/jackson/DiscoverableSubtypeResolver.java
Labels: improvement

#3229 Upgrade to Jackson 2.11.0.rc1
  dropwizard-dependencies/pom.xml
Labels: dependencies

#3236 Configure metrics event listener to track filters
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java
Labels: improvement

#3246 Upgrade to Jackson 2.9.10.20200411
  dropwizard-bom/pom.xml
Labels: security

#3244 Support customizing BootstrapServiceRegistryBuilder
  dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/SessionFactoryFactory.java
  dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/SessionFactoryFactoryTest.java
Labels: improvement

#3256 Remove alpn-boot dependency in dropwizard-http2 for Java 8u252
  dropwizard-http2/pom.xml
Labels: dependencies, improvement

#3259 Upgrade to Liquibase 4.0.0-beta1
  dropwizard-dependencies/pom.xml
Labels: dependencies, java

#3266 Fix typo in dropwizard-archetypes/README.md
  dropwizard-archetypes/README.md
Labels: documentation
