Repository dropwizard/dropwizard, pull requests merged in 2020-10, with the labels that each got.

#3476 Update docs to fix updated methods
  docs/source/manual/hibernate.rst
Labels: documentation

#3483 Fix typos in documentation
  docs/source/about/release-notes.rst
  docs/source/manual/configuration.rst
  docs/source/manual/core.rst
  docs/source/manual/upgrade-notes/upgrade-notes-0_7_x.rst
Labels: documentation

#3485 Enable Dependabot for GitHub Actions
  .github/dependabot.yml
Labels: dependencies

#3504 Upgrade to NullAway 0.8.0
  dropwizard-dependencies/pom.xml
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ValidatingResource.java
Labels: dependencies, java

#3201 UnitOfWork: Support serialized and mixed transactional app
  dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkAspect.java
  dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/TransactionHandlingTest.java
  dropwizard-hibernate/src/test/resources/transaction-handling-test.yaml
Labels: improvement

#3515 Add null-checks to AnnotationSensitivePropertyNamingStrategy
  dropwizard-jackson/src/main/java/io/dropwizard/jackson/AnnotationSensitivePropertyNamingStrategy.java
  dropwizard-jackson/src/test/java/io/dropwizard/jackson/AnnotationSensitivePropertyNamingStrategyTest.java
Labels: bug

#3516 Bump httpclient from 4.5.12 to 4.5.13
  dropwizard-bom/pom.xml
Labels: dependencies, java, security

#3382 Swallow EofException when response was incomplete
  dropwizard-core/src/main/java/io/dropwizard/setup/ExceptionMapperBinder.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/errors/EofExceptionWriterInterceptor.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/errors/EofExceptionWriterInterceptorTest.java
  dropwizard-testing/pom.xml
  dropwizard-testing/src/main/java/io/dropwizard/testing/common/DropwizardTestResourceConfig.java
  dropwizard-testing/src/main/java/io/dropwizard/testing/common/Resource.java
  dropwizard-testing/src/main/java/io/dropwizard/testing/common/ResourceTestJerseyConfiguration.java
Labels: improvement

#3517 Make `driverClass` configuration setting optional
  docs/source/manual/configuration.rst
  dropwizard-db/src/main/java/io/dropwizard/db/DataSourceFactory.java
  dropwizard-db/src/main/java/io/dropwizard/db/PooledDataSourceFactory.java
  dropwizard-db/src/test/java/io/dropwizard/db/DataSourceConfigurationTest.java
  dropwizard-db/src/test/java/io/dropwizard/db/DataSourceFactoryTest.java
  dropwizard-db/src/test/resources/yaml/empty_driver_class_db_pool.yml
Labels: improvement

#3527 Remove obsolete NonblockingServletHolder
  dropwizard-core/src/main/java/io/dropwizard/server/AbstractServerFactory.java
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/NonblockingServletHolder.java
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/setup/ServletEnvironment.java
  dropwizard-jetty/src/test/java/io/dropwizard/jetty/NonblockingServletHolderTest.java
  dropwizard-jetty/src/test/java/io/dropwizard/jetty/setup/ServletEnvironmentTest.java
Labels: improvement

#3535 Run SonarCloud analysis only in dropwizard/dropwizard
  .github/workflows/maven.yml
Labels: task

#3533 Replace invalid default excludedProtocols in HttpsConnectorFactory
  docs/source/manual/configuration.rst
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpsConnectorFactory.java
  dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpsConnectorFactoryTest.java
Labels: bug, security

#3534 Move SonarQube settings to GitHub workflow
  .github/workflows/maven.yml
  pom.xml
Labels: bug

#3536 Prevent deep recursion in ConfigurationMetadata
  dropwizard-configuration/pom.xml
  dropwizard-configuration/src/main/java/io/dropwizard/configuration/ConfigurationMetadata.java
  dropwizard-configuration/src/test/java/io/dropwizard/configuration/ConfigurationMetadataTest.java
Labels: bug
