Repository dropwizard/dropwizard, pull requests merged in 2020-02, with the labels that each got.

#3135 Fix a typo in the fourth paragraph of the Resources -> Methods section of core.rst
  docs/source/manual/core.rst
Labels: documentation

#3157 Escape EL expressions in ViolationCollector
  dropwizard-validation/src/main/java/io/dropwizard/validation/selfvalidating/ViolationCollector.java
  dropwizard-validation/src/test/java/io/dropwizard/validation/SelfValidationTest.java
Labels: security

#3160 Escape EL expressions in ViolationCollector
  dropwizard-validation/src/main/java/io/dropwizard/validation/selfvalidating/ViolationCollector.java
  dropwizard-validation/src/test/java/io/dropwizard/validation/SelfValidationTest.java
Labels: security

#3163 Fix regression in `AbstractParam` handling
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/DefaultValueUtils.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalDoubleParamConverterProvider.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalIntParamConverterProvider.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalLongParamConverterProvider.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/AbstractParam.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/AbstractParamConverter.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/AbstractParamConverterProvider.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ConstraintViolationExceptionMapperTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ValidatingResource.java
Labels: bug

#3168 Upgrade to Jackson 2.9.10.20200223 to address CVE-2020-8840
  dropwizard-bom/pom.xml
Labels: security
