Repository dropwizard/dropwizard, pull requests merged in 2020-08, with the labels that each got.

#3400 ci: mvn --no-transfer-progress
  .github/workflows/maven.yml
Labels: improvement

#3403 Add `--no-transfer-progress` to other Maven invocations
  .circleci/config.yml
  .travis.yml
  appveyor.yml
Labels: improvement

#3433 Upgrade to Jackson 2.9.10.20200824
  dropwizard-bom/pom.xml
Labels: dependencies, java, security

#3431 Handle null values in Optional* ParamConverters
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalDoubleParamConverterProvider.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalIntParamConverterProvider.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalLongParamConverterProvider.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalBeanParamResourceTest.java
Labels: bug
