Repository dropwizard/dropwizard, pull requests merged in 2020-11, with the labels that each got.

#3537 Reduce flakiness of LayoutIntegrationTests
  dropwizard-json-logging/pom.xml
  dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/LayoutIntegrationTests.java
Labels: improvement

#3541 Run SonarCloud analysis only when SONAR_TOKEN is available
  .github/workflows/maven.yml
Labels: github_actions

#3530 Fix logFormat configuration inconsistencies
  docs/source/manual/configuration.rst
  dropwizard-logging/src/main/java/io/dropwizard/logging/AbstractAppenderFactory.java
  dropwizard-logging/src/test/java/io/dropwizard/logging/AppenderFactoryCustomLayoutTest.java
  dropwizard-logging/src/test/java/io/dropwizard/logging/AppenderFactoryCustomTimeZone.java
  dropwizard-logging/src/test/java/io/dropwizard/logging/TestPatternLayoutFactory.java
  dropwizard-logging/src/test/resources/yaml/appender_with_custom_layout_and_format.yml
  dropwizard-logging/src/test/resources/yaml/appender_with_time_zone_placeholder.yml
Labels: bug

#3469 #3468 - Add badge for reproducible build
  README.md
Labels: documentation

#3577 Skip errors when visiting default implementations in ConfigurationMetadata
  dropwizard-configuration/src/main/java/io/dropwizard/configuration/ConfigurationMetadata.java
Labels: bug

#3579 Revert "Replace invalid default excludedProtocols in HttpsConnectorFactory"
  docs/source/manual/configuration.rst
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpsConnectorFactory.java
  dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpsConnectorFactoryTest.java
Labels: improvement
