Repository dropwizard/dropwizard, pull requests merged in 2020-03, with the labels that each got.

#3174 Fix outdated documentation and method signature
  dropwizard-core/src/main/java/io/dropwizard/cli/Cli.java
Labels: documentation

#3197 Update dead link to jersey documentation on filters and interceptors
  docs/source/manual/core.rst
Labels: documentation

#3156 Expose JmxReporter in Bootstrap
  dropwizard-core/src/main/java/io/dropwizard/setup/Bootstrap.java
  dropwizard-core/src/test/java/io/dropwizard/setup/BootstrapTest.java
Labels: improvement

#3202 Enable maven-dependency-plugin analysis
  .github/workflows/maven.yml
  appveyor.yml
  ci/deploy-release.sh
  ci/deploy-snapshot.sh
  dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/pom.xml
  dropwizard-archetypes/src/test/resources/settings.xml
  dropwizard-assets/pom.xml
  dropwizard-auth/pom.xml
  dropwizard-benchmarks/pom.xml
  dropwizard-client/pom.xml
  dropwizard-configuration/pom.xml
  dropwizard-core/pom.xml
  dropwizard-db/pom.xml
  dropwizard-dependencies/pom.xml
  dropwizard-e2e/pom.xml
  dropwizard-e2e/src/test/java/com/example/sslreload/SslReloadAppTest.java
  dropwizard-forms/pom.xml
  dropwizard-hibernate/pom.xml
  dropwizard-http2/pom.xml
  dropwizard-jackson/pom.xml
  dropwizard-jdbi3/pom.xml
  dropwizard-jersey/pom.xml
  dropwizard-jetty/pom.xml
  dropwizard-json-logging/pom.xml
  dropwizard-lifecycle/pom.xml
  dropwizard-logging/pom.xml
  dropwizard-metrics-graphite/pom.xml
  dropwizard-metrics/pom.xml
  dropwizard-migrations/pom.xml
  dropwizard-request-logging/pom.xml
  dropwizard-servlets/pom.xml
  dropwizard-testing/pom.xml
  dropwizard-util/pom.xml
  dropwizard-validation/pom.xml
  dropwizard-views-freemarker/pom.xml
  dropwizard-views-mustache/pom.xml
  dropwizard-views/pom.xml
  pom.xml
Labels: dependencies

#3213 Remove dependency on hk2-bom.
  dropwizard-dependencies/pom.xml
Labels: bug

#3214 Remove release notes for change which went into 2.0.x.
  docs/source/about/release-notes.rst
  docs/source/manual/upgrade-notes.rst
  docs/source/manual/upgrade-notes/upgrade-notes-2_1_x.rst
Labels: documentation

#3216 Make it easier to inherit from dropwizard-parent
  dropwizard-bom/pom.xml
  dropwizard-parent/pom.xml
  pom.xml
Labels: dependencies

#3215 Fix dependency scopes in dropwizard-testing
  dropwizard-example/pom.xml
  dropwizard-testing/pom.xml
Labels: dependencies

#3222 Fix typo in `flattenMdc` field name
  docs/source/manual/configuration.rst
Labels: documentation
