Repository dropwizard/dropwizard, pull requests merged in 2020-09, with the labels that each got.

#3447 Update outdated mockito link
  docs/source/manual/core.rst
Labels: documentation

#3453 Reset Jersey client in tests
  dropwizard-testing/src/main/java/io/dropwizard/testing/junit5/DropwizardAppExtension.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/ReuseDropwizardAppExtensionTestSuite.java
Labels: bug

#3458 ci: add JDK 15
  .github/workflows/maven.yml
Labels: task

#3442 Support parsing system property configuration values as arrays when the field does not exist
  dropwizard-configuration/pom.xml
  dropwizard-configuration/src/main/java/io/dropwizard/configuration/BaseConfigurationFactory.java
  dropwizard-configuration/src/main/java/io/dropwizard/configuration/ConfigurationMetadata.java
  dropwizard-configuration/src/test/java/io/dropwizard/configuration/BaseConfigurationFactoryTest.java
  dropwizard-configuration/src/test/java/io/dropwizard/configuration/ConfigurationMetadataTest.java
  dropwizard-configuration/src/test/java/io/dropwizard/configuration/JsonConfigurationFactoryTest.java
  dropwizard-configuration/src/test/java/io/dropwizard/configuration/YamlConfigurationFactoryTest.java
  dropwizard-configuration/src/test/resources/factory-test-valid-no-type.json
  dropwizard-configuration/src/test/resources/factory-test-valid-no-type.yml
Labels: improvement
