Repository dropwizard/dropwizard, pull requests merged in 2020-07, with the labels that each got.

#3360 Export cache stats in CachingAuthorizer and CachingAuthenticator
  dropwizard-auth/pom.xml
  dropwizard-auth/src/main/java/io/dropwizard/auth/CachingAuthenticator.java
  dropwizard-auth/src/main/java/io/dropwizard/auth/CachingAuthorizer.java
Labels: improvement

#3373 Don't specify scope in dependencyManagement of BOM
  dropwizard-dependencies/pom.xml
Labels: improvement

#3378 Try making App1Test#earlyEofTest() less flaky
  dropwizard-dependencies/pom.xml
  dropwizard-e2e/pom.xml
  dropwizard-e2e/src/test/java/com/example/app1/App1Test.java
Labels: bug

#3379 Removed some conditional tests (test smell)
  dropwizard-validation/src/test/java/io/dropwizard/validation/DataSizeValidatorTest.java
  dropwizard-validation/src/test/java/io/dropwizard/validation/DurationValidatorTest.java
  dropwizard-validation/src/test/java/io/dropwizard/validation/OneOfValidatorTest.java
  dropwizard-validation/src/test/java/io/dropwizard/validation/SizeValidatorTest.java
Labels: improvement

#3372 Swallow EofException when response was incomplete
  dropwizard-core/src/main/java/io/dropwizard/setup/ExceptionMapperBinder.java
  dropwizard-jersey/pom.xml
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/errors/EofExceptionWriterInterceptor.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/errors/EofExceptionWriterInterceptorJerseyTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/errors/EofExceptionWriterInterceptorTest.java
  dropwizard-testing/pom.xml
  dropwizard-testing/src/main/java/io/dropwizard/testing/common/DropwizardTestResourceConfig.java
  dropwizard-testing/src/main/java/io/dropwizard/testing/common/Resource.java
  dropwizard-testing/src/main/java/io/dropwizard/testing/common/ResourceTestJerseyConfiguration.java
Labels: improvement

#3381 Upgrade to Jackson 2.10.5
  dropwizard-dependencies/pom.xml
Labels: dependencies, java

#3392 Upgrade to Liquibase 3.10.2
  dropwizard-dependencies/pom.xml
Labels: dependencies, java

#3389 Bump Maven plugins in java-simple Maven archetype template
  dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/pom.xml
Labels: dependencies, java
