Repository dropwizard/dropwizard, pull requests merged in 2020-05, with the labels that each got.

#3269 Allow overriding default media type in AssetServlet/AssetBundle
  dropwizard-assets/src/main/java/io/dropwizard/assets/AssetsBundle.java
  dropwizard-assets/src/test/java/io/dropwizard/assets/AssetsBundleTest.java
  dropwizard-servlets/src/main/java/io/dropwizard/servlets/assets/AssetServlet.java
  dropwizard-servlets/src/test/java/io/dropwizard/servlets/assets/AssetServletTest.java
Labels: improvement

#3270 Fix random port assignment in Resource
  dropwizard-testing/pom.xml
  dropwizard-testing/src/main/java/io/dropwizard/testing/common/DropwizardTestResourceConfig.java
  dropwizard-testing/src/main/java/io/dropwizard/testing/common/Resource.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/PersonResourceTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/ResourceExtensionMocksTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/ResourceExtensionRandomPortsTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/ResourceExtensionWithJettyTest.java
Labels: bug

#3273 Upgrade to Jackson 2.10.4
  dropwizard-dependencies/pom.xml
Labels: dependencies, java

#3274 Add missing DAOTest#setPassword() method
  dropwizard-example/pom.xml
  dropwizard-example/src/test/java/com/example/helloworld/DockerIntegrationTest.java
  dropwizard-example/src/test/java/com/example/helloworld/db/PersonDAOIntegrationTest.java
  dropwizard-example/src/test/resources/test-docker-example.yml
  dropwizard-testing/src/main/java/io/dropwizard/testing/common/DAOTest.java
Labels: improvement

#3279 Added note on Task.execute method
  docs/source/manual/upgrade-notes/upgrade-notes-2_0_x.rst
Labels: documentation

#3278 Changed signature of Task.execute method
  docs/source/manual/core.rst
Labels: documentation

#3283 Add details on how to configure filterFactories
  docs/source/manual/configuration.rst
Labels: documentation

#3300 Remove unused dependency on Objenesis
  dropwizard-dependencies/pom.xml
Labels: improvement

#3305 Enable reproducible builds
  dropwizard-parent/pom.xml
  pom.xml
Labels: dependencies, improvement
