Repository dropwizard/dropwizard, pull requests merged in 2021-05, with the labels that each got.

#3177 Add example for using HK2 for DI in your project
  docs/source/index.rst
  docs/source/manual/di.rst
Labels: documentation

#3936 Use surefire plugin in archetype compatible with JUnit 5
  dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/pom.xml
Labels: improvement

#3973 AssetServlet: Use MIME type of index file for directory requests
  dropwizard-servlets/src/main/java/io/dropwizard/servlets/assets/AssetServlet.java
Labels: improvement

#3978 Add method to `AbstractDAO` to get `NamedQuery` in a type-safe manner
  docs/source/manual/hibernate.rst
  dropwizard-example/src/main/java/com/example/helloworld/db/PersonDAO.java
  dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/AbstractDAO.java
  dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/AbstractDAOTest.java
Labels: improvement

#3990 Bump Dropwizard Metrics from 4.1.21 to 4.1.22
  dropwizard-dependencies/pom.xml
Labels: dependencies, java

#3997 Implement `expandChildren()` in `ContextRoutingHandler`
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/ContextRoutingHandler.java
Labels: improvement
