Repository dropwizard/dropwizard, pull requests merged in 2021-08, with the labels that each got.

#4191 Bump Maven version to 3.8.2
  .mvn/wrapper/maven-wrapper.properties
Labels: dependencies

#4201 Using Liquibase Scope for providing objects to CustomChanges
  docs/source/manual/migrations.rst
  dropwizard-migrations/src/main/java/io/dropwizard/migrations/DbCommand.java
  dropwizard-migrations/src/main/java/io/dropwizard/migrations/MigrationsBundle.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/LiquibaseScopingTest.java
  dropwizard-migrations/src/test/resources/migrations-custom-change.xml
Labels: feature

#3704 Be stricter when parsing 'Range' headers
  dropwizard-servlets/src/main/java/io/dropwizard/servlets/assets/ByteRange.java
  dropwizard-servlets/src/test/java/io/dropwizard/servlets/assets/ByteRangeTest.java
Labels: stale

#3572 Tighten up tomcat-jdbc dependency in dropwizard-migrations
  dropwizard-migrations/pom.xml
Labels: stale

#3731 Improve dropwizard-migrations tests
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/AbstractMigrationTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbCalculateChecksumCommandTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbClearChecksumsCommandTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbCommandTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbDropAllCommandTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbDumpCommandTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbFastForwardCommandTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbGenerateDocsCommandTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbLocksCommandTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbMigrateCommandTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbMigrateCustomSchemaTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbMigrateDifferentFileCommandTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbPrepareRollbackCommandTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbRollbackCommandTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbStatusCommandTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbTagCommandTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbTestCommandTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/TestMigrationConfiguration.java
Labels: stale
