Repository dropwizard/dropwizard, pull requests merged in 2021-01, with the labels that each got.

#3632 Fix typo in HttpClientBuilder Javadoc
  dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java
Labels: documentation

#3639 Support custom StatsCounter in CachingAuthenticator/CachingAuthorization
  dropwizard-auth/src/main/java/io/dropwizard/auth/CachingAuthenticator.java
  dropwizard-auth/src/main/java/io/dropwizard/auth/CachingAuthorizer.java
Labels: improvement

#3642 Support custom StatsCounter in CachingAuthenticator/CachingAuthorization
  dropwizard-auth/src/main/java/io/dropwizard/auth/CachingAuthenticator.java
  dropwizard-auth/src/main/java/io/dropwizard/auth/CachingAuthorizer.java
Labels: improvement

#3616 Do not print error message about class not found
  dropwizard-configuration/src/main/java/io/dropwizard/configuration/ConfigurationMetadata.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/LogbackExcludedTest.java
Labels: improvement

#3633 Stop ignoring exceptions in dropwizard-logging tests
  dropwizard-logging/src/test/java/io/dropwizard/logging/TcpServer.java
  dropwizard-logging/src/test/java/io/dropwizard/logging/TcpSocketAppenderFactoryTest.java
  dropwizard-logging/src/test/java/io/dropwizard/logging/UdpSocketAppenderFactoryTest.java
Labels: task

#3658 Reduce use of reflection in dropwizard-jetty tests
  dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpsConnectorFactoryTest.java
Labels: task

#3657 Move DropwizardSSLConnectionSocketFactoryTest to io.dropwizard.client
  dropwizard-client/src/main/java/io/dropwizard/client/DropwizardSSLConnectionSocketFactory.java
  dropwizard-client/src/test/java/io/dropwizard/client/DropwizardSSLConnectionSocketFactoryTest.java
Labels: task

#3671 Upgrade to Jersey 2.33
  dropwizard-dependencies/pom.xml
Labels: dependencies, java
