Repository dropwizard/dropwizard, pull requests merged in 2021-12, with the labels that each got.

#4483 Update dependency io.dropwizard.metrics:metrics-bom to v4.1.27
  dropwizard-dependencies/pom.xml
Labels: dependencies, java

#4490 Adjust status code on invalid gzip input
  dropwizard-jetty/pom.xml
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/GzipHandlerFactory.java
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/ZipExceptionHandlingGzipHandler.java
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/ZipExceptionHandlingInputStream.java
  dropwizard-jetty/src/test/java/io/dropwizard/jetty/GzipHandlerTest.java
  dropwizard-jetty/src/test/java/io/dropwizard/jetty/ZipExceptionHandlingInputStreamDelegateTest.java
  dropwizard-jetty/src/test/java/io/dropwizard/jetty/ZipExceptionHandlingInputStreamExceptionTest.java
Labels: bug

#4493 Fix dependency scopes in dropwizard-views-freemarker
  dropwizard-views-freemarker/pom.xml
Labels: dependencies

#4494 Fix dependency scopes in dropwizard-views-freemarker
  dropwizard-views-freemarker/pom.xml
Labels: dependencies

#4496 Update repository URLs for new OSSRH Sonatype instance
  pom.xml
Labels: task

#4495 Update repository URLs for new OSSRH Sonatype instance
  pom.xml
Labels: task

#4519 Remove HSQLDB from tests
  dropwizard-dependencies/pom.xml
  dropwizard-hibernate/pom.xml
  dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/JerseyIntegrationTest.java
  dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/LazyLoadingTest.java
  dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/SessionFactoryFactoryTest.java
  dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/TransactionHandlingTest.java
  dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/UnitOfWorkAwareProxyFactoryTest.java
  dropwizard-hibernate/src/test/resources/hibernate-integration-test.yaml
  dropwizard-hibernate/src/test/resources/transaction-handling-test.yaml
Labels: dependencies

#4526 added useProxyProtocol to the Dropwizard Configuration Reference
  docs/source/manual/configuration.rst
Labels: documentation

#4544 Remove commons-lang3 from dropwizard-jersey
  dropwizard-jersey/pom.xml
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/ConstraintMessage.java
Labels: improvement

#4556 Migrate to official Maven wrapper
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
Labels: dependencies

#4555 Migrate to official Maven wrapper
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
Labels: dependencies

#4557 Publish Maven test results
  .github/workflows/maven.yml
Labels: improvement, github_actions

#4558 Publish Maven test results
  .github/workflows/maven.yml
Labels: improvement, github_actions
