Repository dropwizard/dropwizard, pull requests merged in 2021-09, with the labels that each got.

#4209 Link to example application source code from docs
  docs/source/manual/example.rst
Labels: documentation

#4289 Update dropwizard-client docs
  docs/source/manual/client.rst
Labels: documentation

#4259 Build with Java 17 and migrate to actions/setup-java
  .github/workflows/maven.yml
  dropwizard-client/src/test/java/io/dropwizard/client/DropwizardSSLConnectionSocketFactoryTest.java
  dropwizard-parent/pom.xml
Labels: improvement

#4260 Build with Java 17 and migrate to actions/setup-java
  .github/workflows/maven.yml
  dropwizard-client/src/test/java/io/dropwizard/client/DropwizardSSLConnectionSocketFactoryTest.java
  dropwizard-parent/pom.xml
Labels: improvement

#4299 Enable `DropwizardSSLConnectionSocketFactoryTest`
  dropwizard-client/src/test/java/io/dropwizard/client/DropwizardSSLConnectionSocketFactoryTest.java
Labels: bug

#4297 Add workflow to build Sphinx documentation on PRs
  .github/workflows/docs.yml
  docs/source/about/release-notes.rst
  docs/source/manual/configuration.rst
  docs/source/manual/core.rst
Labels: documentation, github_actions

#4300 Exclude `javax.servlet:javax.servlet-api` from Jetty dependencies
  dropwizard-core/pom.xml
  dropwizard-http2/pom.xml
  dropwizard-jetty/pom.xml
Labels: bug, dependencies
