Repository dropwizard/dropwizard, pull requests merged in 2021-02, with the labels that each got.

#3673 Add support for testing plain Command classes
  dropwizard-core/src/main/java/io/dropwizard/cli/ConfiguredCommand.java
  dropwizard-core/src/main/java/io/dropwizard/cli/EnvironmentCommand.java
  dropwizard-e2e/src/main/java/com/example/badlog/BadLogApp.java
  dropwizard-e2e/src/test/java/com/example/badlog/BadLogTest.java
  dropwizard-testing/src/main/java/io/dropwizard/testing/DropwizardTestSupport.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/DropwizardAppExtensionWithCheckCommandTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/DropwizardAppExtensionWithConfiguredCommandTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/DropwizardAppExtensionWithCustomCommandTest.java
Labels: improvement

#3675 Clarify the need of calling super from ConfiguredCommand
  docs/source/manual/core.rst
Labels: documentation

#3723 Bump tomcat-jdbc from 9.0.41 to 9.0.43
  dropwizard-dependencies/pom.xml
Labels: dependencies, java
