Repository dropwizard/dropwizard, pull requests merged in 2021-03, with the labels that each got.

#3774 Remove explicit scope in dropwizard-dependencies
  dropwizard-dependencies/pom.xml
  dropwizard-hibernate/pom.xml
  dropwizard-testing/pom.xml
Labels: bug

#3787 Support "purging" the GitHub workflow cache
  .github/workflows/maven.yml
  .github/workflows/release.yml
Labels: github_actions

#3788 Build Dropwizard with Java 16
  .github/workflows/maven.yml
  dropwizard-example/src/test/java/com/example/helloworld/DockerIntegrationTest.java
  dropwizard-example/src/test/java/com/example/helloworld/db/PersonDAOIntegrationTest.java
  dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpsConnectorFactoryTest.java
  dropwizard-parent/pom.xml
Labels: dependencies, java

#3786 Properly support HTTP/1.1 in Http2ConnectorFactory
  dropwizard-http2/pom.xml
  dropwizard-http2/src/main/java/io/dropwizard/http2/Http2ConnectorFactory.java
  dropwizard-http2/src/test/java/io/dropwizard/http2/AbstractHttp2Test.java
  dropwizard-http2/src/test/java/io/dropwizard/http2/Http2CIntegrationTest.java
  dropwizard-http2/src/test/java/io/dropwizard/http2/Http2ConnectorFactoryTest.java
  dropwizard-http2/src/test/java/io/dropwizard/http2/Http2IntegrationTest.java
  dropwizard-http2/src/test/java/io/dropwizard/http2/Http2WithConscrypt.java
  dropwizard-http2/src/test/java/io/dropwizard/http2/Http2WithCustomCipherTest.java
Labels: bug

#3736 Fixed incorrect cache behaviour (#3724)
  dropwizard-servlets/src/main/java/io/dropwizard/servlets/assets/AssetServlet.java
  dropwizard-servlets/src/test/java/io/dropwizard/servlets/assets/AssetServletTest.java
Labels: bug

#3725 Support using custom AuthorizationContext
  dropwizard-auth/src/main/java/io/dropwizard/auth/AuthorizationContext.java
  dropwizard-auth/src/main/java/io/dropwizard/auth/Authorizer.java
  dropwizard-auth/src/main/java/io/dropwizard/auth/CachingAuthorizer.java
  dropwizard-auth/src/main/java/io/dropwizard/auth/DefaultAuthorizationContext.java
  dropwizard-auth/src/test/java/io/dropwizard/auth/CachingAuthorizerTest.java
Labels: improvement

#3800 Ensure correct TreeTraversingParser initialization in BaseConfigurationFactory
  dropwizard-configuration/src/main/java/io/dropwizard/configuration/BaseConfigurationFactory.java
  dropwizard-configuration/src/test/java/io/dropwizard/configuration/Issue3796Test.java
  dropwizard-configuration/src/test/resources/issue-3796.yml
Labels: bug

#3803 Replace Jackson Afterburner with Blackbird
  dropwizard-jackson/pom.xml
  dropwizard-jackson/src/main/java/io/dropwizard/jackson/Jackson.java
Labels: improvement
