Repository dropwizard/dropwizard, pull requests merged in 2021-06, with the labels that each got.

#4018 Add @JsonProperty for field layout getter/setter
  dropwizard-logging/src/main/java/io/dropwizard/logging/AbstractAppenderFactory.java
Labels: bug

#4024 [Docs] Add link to xvik/dropwizard-guicey
  docs/source/manual/di.rst
Labels: documentation

#4030 Added clarifying note on Singleton annotation
  docs/source/manual/di.rst
Labels: documentation

#4067 Add support for HTTP/2 over TLSv1.3
  dropwizard-http2/src/main/java/io/dropwizard/http2/Http2ConnectorFactory.java
Labels: bug

#4077 Upgrade to Dropwizard Metrics 4.1.23
  dropwizard-core/pom.xml
  dropwizard-dependencies/pom.xml
Labels: dependencies, java

#4085 Upgrade to Dropwizard Metrics 4.2.2
  dropwizard-dependencies/pom.xml
Labels: dependencies, java

#4084 Upgrade to Dropwizard Metrics 4.1.24
  dropwizard-dependencies/pom.xml
Labels: dependencies, java
