Repository dropwizard/dropwizard, pull requests merged in 2022-09, with the labels that each got.

#5781 Update logback to version 1.3.0
  dropwizard-dependencies/pom.xml
  dropwizard-logging/src/main/java/io/dropwizard/logging/common/DefaultLoggingFactory.java
  dropwizard-request-logging/src/main/java/io/dropwizard/request/logging/LogbackAccessRequestLog.java
  dropwizard-request-logging/src/test/java/io/dropwizard/request/logging/layout/SafeRequestParameterConverterTest.java
Labels: dependencies

#5778 Address errorprone warnings in dropwizard-logging
  dropwizard-logging/src/main/java/io/dropwizard/logging/AbstractAppenderFactory.java
  dropwizard-logging/src/main/java/io/dropwizard/logging/DefaultLoggingFactory.java
  dropwizard-logging/src/main/java/io/dropwizard/logging/FileAppenderFactory.java
Labels: task

#5814 Exclude `jetty-servlet-api`
  dropwizard-e2e/pom.xml
  dropwizard-health/pom.xml
  dropwizard-json-logging/pom.xml
  dropwizard-lifecycle/pom.xml
  dropwizard-parent/pom.xml
  dropwizard-testing/pom.xml
Labels: task

#5822 Update upgrade notes for 3.0.0
  docs/source/manual/upgrade-notes/upgrade-notes-3_0_x.rst
Labels: documentation

#5825 Only configure JMX, if the JMXConfigurator is present
  dropwizard-logging/src/main/java/io/dropwizard/logging/DefaultLoggingFactory.java
Labels: improvement

#5725 Disable check for static keyword on SLF4J loggers
  dropwizard-parent/pom.xml
Labels: task

#5855 Drop support for Java 8 in dropwizard-jersey
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java
  dropwizard-util/src/main/java/io/dropwizard/util/JavaVersion.java
  dropwizard-util/src/test/java/io/dropwizard/util/JavaVersionTest.java
Labels: improvement

#5872 Exchange HTTP client implementation
  dropwizard-testing/pom.xml
  dropwizard-testing/src/main/java/io/dropwizard/testing/junit5/DropwizardAppExtension.java
Labels: task

#5854 Improve startup performance for many loggers
  dropwizard-logging/src/main/java/io/dropwizard/logging/DefaultLoggingFactory.java
Labels: improvement

#5882 Update link to Jackson's polymorphic deserialization docs
  docs/source/manual/configuration.rst
Labels: documentation

#5871 Upgrade to hibernate-core 6.1.3
  dropwizard-dependencies/pom.xml
  dropwizard-hibernate/pom.xml
  dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/AbstractDAO.java
  dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/SessionFactoryFactory.java
  dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/dual/DualSessionFactory.java
  dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/AbstractDAOTest.java
  dropwizard-testing/pom.xml
  dropwizard-testing/src/main/java/io/dropwizard/testing/common/DAOTest.java
Labels: feature

#5880 Expose MethodInterceptor and the invoke method
  dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkAwareProxyFactory.java
Labels: bug

#5749 JavaDoc enhancements
  dropwizard-configuration/src/main/java/io/dropwizard/configuration/BaseConfigurationFactory.java
  dropwizard-configuration/src/main/java/io/dropwizard/configuration/ConfigurationException.java
  dropwizard-configuration/src/main/java/io/dropwizard/configuration/ConfigurationFactory.java
  dropwizard-configuration/src/main/java/io/dropwizard/configuration/ConfigurationFactoryFactory.java
  dropwizard-configuration/src/main/java/io/dropwizard/configuration/ConfigurationMetadata.java
  dropwizard-configuration/src/main/java/io/dropwizard/configuration/ConfigurationParsingException.java
  dropwizard-configuration/src/main/java/io/dropwizard/configuration/ConfigurationValidationException.java
  dropwizard-configuration/src/main/java/io/dropwizard/configuration/DefaultConfigurationFactoryFactory.java
  dropwizard-configuration/src/main/java/io/dropwizard/configuration/EnvironmentVariableSubstitutor.java
  dropwizard-configuration/src/main/java/io/dropwizard/configuration/UndefinedEnvironmentVariableException.java
  dropwizard-jackson/src/main/java/io/dropwizard/jackson/AnnotationSensitivePropertyNamingStrategy.java
  dropwizard-jackson/src/main/java/io/dropwizard/jackson/CaffeineModule.java
  dropwizard-jackson/src/main/java/io/dropwizard/jackson/DiscoverableSubtypeResolver.java
  dropwizard-jackson/src/main/java/io/dropwizard/jackson/FuzzyEnumModule.java
  dropwizard-jackson/src/main/java/io/dropwizard/jackson/GuavaExtrasModule.java
  dropwizard-jackson/src/main/java/io/dropwizard/jackson/Jackson.java
  dropwizard-util/src/main/java/io/dropwizard/util/ByteStreams.java
  dropwizard-util/src/main/java/io/dropwizard/util/CharStreams.java
  dropwizard-util/src/main/java/io/dropwizard/util/DataSize.java
  dropwizard-util/src/main/java/io/dropwizard/util/DirectExecutorService.java
  dropwizard-util/src/main/java/io/dropwizard/util/Duration.java
  dropwizard-util/src/main/java/io/dropwizard/util/Enums.java
  dropwizard-util/src/main/java/io/dropwizard/util/JarLocation.java
  dropwizard-util/src/main/java/io/dropwizard/util/JavaVersion.java
  dropwizard-util/src/main/java/io/dropwizard/util/Lists.java
  dropwizard-util/src/main/java/io/dropwizard/util/Maps.java
  dropwizard-util/src/main/java/io/dropwizard/util/Optionals.java
  dropwizard-util/src/main/java/io/dropwizard/util/Resources.java
  dropwizard-util/src/main/java/io/dropwizard/util/Sets.java
  dropwizard-util/src/main/java/io/dropwizard/util/Size.java
  dropwizard-util/src/main/java/io/dropwizard/util/Strings.java
  dropwizard-util/src/main/java/io/dropwizard/util/Throwables.java
  dropwizard-validation/src/main/java/io/dropwizard/validation/BaseValidator.java
  dropwizard-validation/src/main/java/io/dropwizard/validation/ConstraintViolations.java
  dropwizard-validation/src/main/java/io/dropwizard/validation/DataSizeRange.java
  dropwizard-validation/src/main/java/io/dropwizard/validation/DurationRange.java
  dropwizard-validation/src/main/java/io/dropwizard/validation/InterpolationHelper.java
  dropwizard-validation/src/main/java/io/dropwizard/validation/MaxDataSize.java
  dropwizard-validation/src/main/java/io/dropwizard/validation/MaxDuration.java
  dropwizard-validation/src/main/java/io/dropwizard/validation/MaxSize.java
  dropwizard-validation/src/main/java/io/dropwizard/validation/MinDataSize.java
  dropwizard-validation/src/main/java/io/dropwizard/validation/MinDuration.java
  dropwizard-validation/src/main/java/io/dropwizard/validation/MinSize.java
  dropwizard-validation/src/main/java/io/dropwizard/validation/OneOf.java
  dropwizard-validation/src/main/java/io/dropwizard/validation/OneOfValidator.java
  dropwizard-validation/src/main/java/io/dropwizard/validation/PortRange.java
  dropwizard-validation/src/main/java/io/dropwizard/validation/SizeRange.java
  dropwizard-validation/src/main/java/io/dropwizard/validation/ValidationMethod.java
  dropwizard-validation/src/main/java/io/dropwizard/validation/selfvalidating/SelfValidating.java
  dropwizard-validation/src/main/java/io/dropwizard/validation/selfvalidating/SelfValidatingValidator.java
  dropwizard-validation/src/main/java/io/dropwizard/validation/selfvalidating/ValidationCaller.java
  dropwizard-validation/src/main/java/io/dropwizard/validation/selfvalidating/ViolationCollector.java
  dropwizard-validation/src/main/java/io/dropwizard/validation/valuehandling/GuavaOptionalValueExtractor.java
Labels: documentation, improvement

#5681 Expose `ManagedDataSource` to provide access to the connection pool
  dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/SessionFactoryManager.java
Labels: improvement
