Repository dropwizard/dropwizard, pull requests merged in 2022-12, with the labels that each got.

#6303 Merge Renovate PRs automatically (patch only)
  renovate.json
Labels: dependencies

#6304 Merge Renovate PRs automatically (patch only)
  renovate.json
Labels: dependencies

#6305 Merge Renovate PRs automatically (patch only)
  renovate.json
Labels: dependencies

#6306 Merge Renovate PRs automatically (patch only)
  renovate.json
Labels: dependencies

#6267 Cache proxy classes
  dropwizard-hibernate/pom.xml
  dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkAwareProxyFactory.java
Labels: improvement

#6214 Add migration guide for Dropwizard 4.0.x
  docs/source/manual/upgrade-notes.rst
  docs/source/manual/upgrade-notes/upgrade-notes-4_0_x.rst
Labels: documentation

#6404 Adjust tests to different optional behaviour of Jersey 2.38
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalCookieParamResourceTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalFormParamResourceTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalHeaderParamResourceTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalQueryParamResourceTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ConstraintViolationExceptionMapperTest.java
Labels: task, dependencies

#6405 Adjust tests to different optional behaviour of Jersey 2.38
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalCookieParamResourceTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalFormParamResourceTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalHeaderParamResourceTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalQueryParamResourceTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ConstraintViolationExceptionMapperTest.java
Labels: task, dependencies
