Repository dropwizard/dropwizard, pull requests merged in 2022-01, with the labels that each got.

#4571 Small test enhancements
  dropwizard-e2e/src/test/java/com/example/health/HealthIntegrationTest.java
  dropwizard-health/src/test/java/io/dropwizard/health/StateTest.java
  dropwizard-jetty/src/test/java/io/dropwizard/jetty/GzipHandlerFactoryTest.java
  dropwizard-lifecycle/pom.xml
  dropwizard-lifecycle/src/test/java/io/dropwizard/lifecycle/setup/ExecutorServiceBuilderTest.java
Labels: improvement

#4584 Mark dropwizard-jetty's `NetUtil` deprecated
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/NetUtil.java
Labels: task

#4585 Update HK2's repackaged jakarta.inject to jakarta.inject-api
  dropwizard-auth/pom.xml
  dropwizard-core/pom.xml
  dropwizard-dependencies/pom.xml
  dropwizard-jersey/pom.xml
Labels: improvement, dependencies, java

#4593 Clarify support for Dropwizard 1.3.x in security policy
  SECURITY.md
Labels: documentation

#4617 Clarify that maxRequestHeaderSize is a combined limit for all headers
  docs/source/manual/configuration.rst
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpConnectorFactory.java
Labels: documentation

#4636 Remove duplicate logfile from dropwizard-logging tests (#4568)
  dropwizard-logging/src/test/resources/yaml/logging.yml
Labels: improvement
