Repository dropwizard/dropwizard, pull requests merged in 2022-02, with the labels that each got.

#4681 Provide documentation for session support
  docs/source/manual/core.rst
  dropwizard-e2e/pom.xml
  dropwizard-e2e/src/main/java/com/example/httpsessions/HttpSessionsApp.java
  dropwizard-e2e/src/main/java/com/example/httpsessions/HttpSessionsResource.java
  dropwizard-e2e/src/test/java/com/example/httpsessions/HttpSessionsTest.java
  dropwizard-e2e/src/test/resources/httpsessions/config.yml
Labels: documentation

#4680 Extend DAOTestExtension with junit5 callbacks
  dropwizard-testing/src/main/java/io/dropwizard/testing/junit5/DAOTestExtension.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/DAOTestExtensionRegisterExtensionTest.java
Labels: improvement

#4725 Set baseline to Java 11 and update CI workflows accordingly
  .github/workflows/maven.yml
  .github/workflows/release.yml
  dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/pom.xml
  dropwizard-example/pom.xml
  dropwizard-parent/pom.xml
Labels: task

#4726 Set baseline to Java 11 and update CI workflows accordingly
  .github/workflows/maven.yml
  .github/workflows/release.yml
  dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/pom.xml
  dropwizard-example/pom.xml
  dropwizard-parent/pom.xml
Labels: task

#4740 Revert "Set baseline to Java 11 and update CI workflows accordingly"
  .github/workflows/maven.yml
  .github/workflows/release.yml
  dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/pom.xml
  dropwizard-example/pom.xml
  dropwizard-parent/pom.xml
Labels: task

#4741 Set baseline to Java 11 and update CI workflows accordingly
  .github/workflows/maven.yml
  .github/workflows/release.yml
  dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/pom.xml
  dropwizard-example/pom.xml
  dropwizard-parent/pom.xml
Labels: task

#4743 Clean up Error Prone configuration
  .mvn/jvm.config
  dropwizard-parent/pom.xml
Labels: task

#4742 Clean up Error Prone configuration
  .mvn/jvm.config
  dropwizard-parent/pom.xml
Labels: task

#4831 Explain/remove empty methods
  dropwizard-client/src/main/java/io/dropwizard/client/DropwizardExecutorProvider.java
  dropwizard-core/src/main/java/io/dropwizard/cli/Cli.java
  dropwizard-e2e/src/main/java/com/example/health/HealthApp.java
  dropwizard-e2e/src/main/java/com/example/sslreload/SslReloadApp.java
  dropwizard-e2e/src/main/java/com/example/validation/WasInjectedConstraintValidator.java
  dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/SessionFactoryFactory.java
  dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkApplicationListener.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/filter/AllowedMethodsFilter.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/MutableValidatorFactory.java
  dropwizard-logging/src/main/java/io/dropwizard/logging/ExternalLoggingFactory.java
  dropwizard-validation/src/main/java/io/dropwizard/validation/MethodValidator.java
Labels: improvement
