Repository dropwizard/dropwizard, pull requests merged in 2022-04, with the labels that each got.

#5093 Replace JAX-RS ClientBuilder with Jersey's JerseyClientBuilder
  dropwizard-client/src/main/java/io/dropwizard/client/JerseyClientBuilder.java
  dropwizard-health/src/main/java/io/dropwizard/health/check/http/HttpHealthCheck.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/DropwizardTestSupportTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/AbstractDropwizardAppExtensionTest.java
Labels: improvement

#4198 Repeatable `@UnitOfWork` annotation
  docs/source/manual/hibernate.rst
  dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWork.java
  dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkApplicationListener.java
  dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkAwareProxyFactory.java
  dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitsOfWork.java
  dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/MultipleUnitOfWorkTest.java
  dropwizard-hibernate/src/test/resources/hibernate-multiple-unitofwork.yaml
Labels: feature

#5026 Provide method to override exception type for auth filters
  dropwizard-auth/src/main/java/io/dropwizard/auth/UnauthorizedHandler.java
  dropwizard-auth/src/main/java/io/dropwizard/auth/basic/BasicCredentialAuthFilter.java
  dropwizard-auth/src/main/java/io/dropwizard/auth/chained/ChainedAuthFilter.java
  dropwizard-auth/src/main/java/io/dropwizard/auth/oauth/OAuthCredentialAuthFilter.java
  dropwizard-auth/src/test/java/io/dropwizard/auth/CustomAuthExceptionTest.java
Labels: improvement

#4563 Provide dependency injection for auth filter objects
  dropwizard-auth/src/main/java/io/dropwizard/auth/AuthDynamicFeature.java
  dropwizard-auth/src/main/java/io/dropwizard/auth/InjectingFilter.java
  dropwizard-auth/src/main/java/io/dropwizard/auth/PolymorphicAuthDynamicFeature.java
  dropwizard-auth/src/main/java/io/dropwizard/auth/WebApplicationExceptionCatchingFilter.java
  dropwizard-auth/src/test/java/io/dropwizard/auth/InjectionTest.java
Labels: feature

#3580 Hibernate: DualSessionFactory
  dropwizard-hibernate/pom.xml
  dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/HibernateBundle.java
  dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkAspect.java
  dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/dual/DualSessionFactory.java
  dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/dual/HibernateBundle.java
  dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/dual/DualSessionFactoryTest.java
  dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/dual/HibernateBundleTest.java
Labels: feature

#5115 Properly stop threads of `LogbackAccessRequestLog`
  dropwizard-request-logging/src/main/java/io/dropwizard/request/logging/LogbackAccessRequestLog.java
Labels: improvement

#5010 Jetty 10
  docs/source/manual/configuration.rst
  dropwizard-client/src/test/resources/yaml/ssl_connection_socket_factory_test.yml
  dropwizard-core/pom.xml
  dropwizard-core/src/main/java/io/dropwizard/core/cli/ServerCommand.java
  dropwizard-core/src/main/java/io/dropwizard/core/server/AbstractServerFactory.java
  dropwizard-core/src/main/java/io/dropwizard/core/server/DefaultServerFactory.java
  dropwizard-core/src/main/java/io/dropwizard/core/setup/AdminEnvironment.java
  dropwizard-core/src/main/java/io/dropwizard/core/sslreload/SslReloadBundle.java
  dropwizard-dependencies/pom.xml
  dropwizard-e2e/src/test/resources/sslreload/config.yml
  dropwizard-health/pom.xml
  dropwizard-http2/pom.xml
  dropwizard-http2/src/main/java/io/dropwizard/http2/Http2CConnectorFactory.java
  dropwizard-http2/src/main/java/io/dropwizard/http2/Http2ConnectorFactory.java
  dropwizard-http2/src/test/java/io/dropwizard/http2/Http2CIntegrationTest.java
  dropwizard-http2/src/test/java/io/dropwizard/http2/Http2TestCommon.java
  dropwizard-http2/src/test/resources/test-http2-with-conscrypt.yml
  dropwizard-http2/src/test/resources/test-http2-with-custom-cipher.yml
  dropwizard-http2/src/test/resources/test-http2.yml
  dropwizard-jersey/pom.xml
  dropwizard-jetty/pom.xml
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/ContextRoutingHandler.java
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/GzipHandlerFactory.java
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpConnectorFactory.java
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpsConnectorFactory.java
  dropwizard-jetty/src/test/java/io/dropwizard/jetty/GzipHandlerFactoryTest.java
  dropwizard-jetty/src/test/java/io/dropwizard/jetty/GzipHandlerTest.java
  dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpConnectorFactoryTest.java
  dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpsConnectorFactoryTest.java
  dropwizard-jetty/src/test/resources/yaml/gzip.yml
  dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/LayoutIntegrationTests.java
  dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/setup/LifecycleEnvironment.java
  dropwizard-lifecycle/src/test/java/io/dropwizard/lifecycle/setup/LifecycleEnvironmentTest.java
  dropwizard-request-logging/pom.xml
  dropwizard-request-logging/src/main/java/io/dropwizard/request/logging/DropwizardJettyServerAdapter.java
  dropwizard-request-logging/src/main/java/io/dropwizard/request/logging/LogbackAccessRequestLog.java
  dropwizard-request-logging/src/test/java/io/dropwizard/request/logging/LogbackAccessRequestLogTest.java
  dropwizard-request-logging/src/test/java/io/dropwizard/request/logging/old/DropwizardSlf4jRequestLogWriterTest.java
  dropwizard-servlets/pom.xml
  dropwizard-servlets/src/test/java/io/dropwizard/servlets/assets/AssetServletTest.java
Labels: dependencies, java

#5137 Revert "Add automatic module names for all Dropwizard modules"
  dropwizard-assets/pom.xml
  dropwizard-auth/pom.xml
  dropwizard-client/pom.xml
  dropwizard-configuration/pom.xml
  dropwizard-core/pom.xml
  dropwizard-db/pom.xml
  dropwizard-forms/pom.xml
  dropwizard-health/pom.xml
  dropwizard-hibernate/pom.xml
  dropwizard-http2/pom.xml
  dropwizard-jackson/pom.xml
  dropwizard-jdbi3/pom.xml
  dropwizard-jersey/pom.xml
  dropwizard-jetty/pom.xml
  dropwizard-json-logging/pom.xml
  dropwizard-lifecycle/pom.xml
  dropwizard-logging/pom.xml
  dropwizard-metrics-graphite/pom.xml
  dropwizard-metrics/pom.xml
  dropwizard-migrations/pom.xml
  dropwizard-parent/pom.xml
  dropwizard-request-logging/pom.xml
  dropwizard-servlets/pom.xml
  dropwizard-testing/pom.xml
  dropwizard-util/pom.xml
  dropwizard-validation/pom.xml
  dropwizard-views-freemarker/pom.xml
  dropwizard-views-mustache/pom.xml
  dropwizard-views/pom.xml
Labels: task

#5149 Replace `@NotThreadSafe` with jUnit 5 `Execution(SAME_THREAD)`
  dropwizard-dependencies/pom.xml
  dropwizard-migrations/pom.xml
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/CloseableLiquibaseTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbCalculateChecksumCommandTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbClearChecksumsCommandTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbCommandTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbDropAllCommandTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbDumpCommandTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbFastForwardCommandTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbGenerateDocsCommandTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbLocksCommandTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbMigrateCommandTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbMigrateCustomSchemaTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbMigrateDifferentFileCommandTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbPrepareRollbackCommandTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbRollbackCommandTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbStatusCommandTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbTagCommandTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbTestCommandTest.java
Labels: improvement

#5159 Set permissions for GitHub actions
  .github/workflows/close_stale.yml
Labels: improvement, github_actions

#5169 Migrations file handling
  dropwizard-migrations/src/main/java/io/dropwizard/migrations/CloseableLiquibaseWithFileSystemMigrationsFile.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbMigrateDifferentFileCommandTest.java
Labels: bug

#5197 rework auth filter injection behavior to only setup injection once at startup
  dropwizard-auth/src/main/java/io/dropwizard/auth/AuthDynamicFeature.java
  dropwizard-auth/src/main/java/io/dropwizard/auth/AuthInjectionHelper.java
  dropwizard-auth/src/main/java/io/dropwizard/auth/InjectingFilter.java
  dropwizard-auth/src/main/java/io/dropwizard/auth/PolymorphicAuthDynamicFeature.java
  dropwizard-auth/src/main/java/io/dropwizard/auth/WebApplicationExceptionCatchingFilter.java
  dropwizard-auth/src/test/java/io/dropwizard/auth/AuthDynamicFeatureAuthFilterInjectionTest.java
  dropwizard-auth/src/test/java/io/dropwizard/auth/AuthDynamicFeatureInjectionTest.java
  dropwizard-auth/src/test/java/io/dropwizard/auth/InjectionTest.java
Labels: improvement

#5201 Update link to Apache HttpClient's docs
  docs/source/manual/client.rst
Labels: documentation

#5231 Add notes for breaking changes in Jersey and Liquibase
  docs/source/manual/upgrade-notes/upgrade-notes-2_1_x.rst
Labels: documentation
