Repository dropwizard/dropwizard, pull requests merged in 2022-06, with the labels that each got.

#5385 Generate SBOM for Dropwizard using CycloneDX Maven plugin
  dropwizard-benchmarks/pom.xml
  dropwizard-e2e/pom.xml
  pom.xml
Labels: task, security

#5388 Generate SBOM for Dropwizard using CycloneDX Maven plugin
  dropwizard-benchmarks/pom.xml
  dropwizard-e2e/pom.xml
  pom.xml
Labels: task, security

#5413 Update maven-enforcer-plugin to v3.1.0
  dropwizard-example/pom.xml
  dropwizard-hibernate/pom.xml
  pom.xml
Labels: task, dependencies

#5419 Fix CycloneDX execution
  pom.xml
Labels: bug

#5420 Windows runners
  .github/workflows/maven.yml
  dropwizard-client/src/test/java/io/dropwizard/client/DropwizardSSLConnectionSocketFactoryTest.java
Labels: task

#5430 Use Visual Studio 2022 image and Java 17 on AppVeyor
  appveyor.yml
Labels: task

#5138 Remove jUnit 4.x support
  docs/source/manual/testing.rst
  docs/source/manual/upgrade-notes/upgrade-notes-3_0_x.rst
  dropwizard-dependencies/pom.xml
  dropwizard-testing/pom.xml
  dropwizard-testing/src/main/java/io/dropwizard/testing/junit/DAOTestRule.java
  dropwizard-testing/src/main/java/io/dropwizard/testing/junit/DropwizardAppRule.java
  dropwizard-testing/src/main/java/io/dropwizard/testing/junit/DropwizardClientRule.java
  dropwizard-testing/src/main/java/io/dropwizard/testing/junit/MockitoTestRule.java
  dropwizard-testing/src/main/java/io/dropwizard/testing/junit/ResourceTestRule.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/app/GzipDefaultVaryBehaviourTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/app/PersonResourceExceptionMapperTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/app/ResourceTestRuleTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/app/ResourceTestRuleWithGrizzlyTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/app/ResourceTestRuleWithoutLoggingBootstrapTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DAOTestRuleConfigTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DAOTestRuleTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DAOTestRuleWithoutLoggingBootstrapTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleConfigOverrideTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleReentrantTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleResetConfigOverrideTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleWithExplicitTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleWithoutConfigTest.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardClientRuleTest.java
Labels: task, improvement

#5464 Change access modifier of `@UnitsOfWork` to public
  dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitsOfWork.java
Labels: bug

#5477 Revert "Replace Jackson Afterburner with Blackbird"
  docs/source/manual/upgrade-notes/upgrade-notes-2_1_x.rst
  dropwizard-jackson/pom.xml
  dropwizard-jackson/src/main/java/io/dropwizard/jackson/Jackson.java
  dropwizard-jackson/src/test/java/io/dropwizard/jackson/JacksonTest.java
Labels: improvement
