Repository dropwizard/dropwizard, pull requests merged in 2022-08, with the labels that each got.

#5638 Replace `org.glassfish.hk2.external:jakarta.inject` with `jakarta.inject:jakarta.inject-api`
  dropwizard-auth/pom.xml
  dropwizard-benchmarks/pom.xml
  dropwizard-client/pom.xml
  dropwizard-core/pom.xml
  dropwizard-e2e/pom.xml
  dropwizard-health/pom.xml
  dropwizard-hibernate/pom.xml
  dropwizard-jersey/pom.xml
  dropwizard-parent/pom.xml
  dropwizard-testing/pom.xml
  dropwizard-views-freemarker/pom.xml
  dropwizard-views-mustache/pom.xml
  dropwizard-views/pom.xml
Labels: task

#5690 Properly handle `null` in PortRangeValidator
  dropwizard-validation/src/main/java/io/dropwizard/validation/PortRangeValidator.java
  dropwizard-validation/src/test/java/io/dropwizard/validation/PortRangeValidatorTest.java
Labels: bug

#5689 Properly handle `null` in PortRangeValidator
  dropwizard-validation/src/main/java/io/dropwizard/validation/PortRangeValidator.java
  dropwizard-validation/src/test/java/io/dropwizard/validation/PortRangeValidatorTest.java
Labels: bug

#5692 Add toJavaDuration to Duration
  dropwizard-util/src/main/java/io/dropwizard/util/Duration.java
  dropwizard-util/src/test/java/io/dropwizard/util/DurationTest.java
Labels: improvement

#5712 Remove guava exclusion from mustache dependency
  dropwizard-dependencies/pom.xml
Labels: dependencies

#5713 Remove deprecated EnvironmentVariableLookup
  dropwizard-configuration/src/main/java/io/dropwizard/configuration/EnvironmentVariableLookup.java
  dropwizard-configuration/src/test/java/io/dropwizard/configuration/EnvironmentVariableLookupTest.java
Labels: task

#5506 Wrap exceptions thrown by beforeStart with MappableException
  dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkApplicationListener.java
  dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/JdbcSQLNonTransientConnectionExceptionMapper.java
  dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/JerseyIntegrationTest.java
  dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/UnitOfWorkApplicationListenerTest.java
Labels: improvement

#5691 Allow parameter conversion exceptions to be mapped to responses by exception mappers
  docs/source/manual/upgrade-notes/upgrade-notes-2_1_x.rst
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/AbstractParam.java
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/FuzzyEnumParamConverter.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/BooleanParamTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/DurationParamTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/InstantParamTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/IntParamTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/LongParamTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/SizeParamTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/UUIDParamTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ConstraintViolationExceptionMapperTest.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/FuzzyEnumParamConverterProviderTest.java
Labels: bug

#5716 Suppress logging during dropwizard-validations tests
  dropwizard-validation/src/test/java/io/dropwizard/validation/SelfValidationTest.java
  dropwizard-validation/src/test/resources/logback-test.xml
Labels: improvement

#5771 Minimise test logging configuration
  dropwizard-auth/src/test/resources/logback-test.xml
  dropwizard-client/src/test/resources/logback-test.xml
  dropwizard-configuration/src/test/resources/logback-test.xml
  dropwizard-core/src/test/resources/logback-test.xml
  dropwizard-db/src/test/resources/logback-test.xml
  dropwizard-hibernate/src/test/resources/logback-test.xml
  dropwizard-jersey/src/test/resources/logback-test.xml
  dropwizard-jetty/src/test/resources/logback-test.xml
  dropwizard-lifecycle/src/test/resources/logback-test.xml
  dropwizard-logging/src/test/resources/logback-test.xml
  dropwizard-migrations/src/test/resources/logback-test.xml
  dropwizard-servlets/src/test/resources/logback-test.xml
  dropwizard-testing/src/test/resources/logback-test.xml
  dropwizard-validation/src/test/resources/logback-test.xml
  dropwizard-views-freemarker/src/test/resources/logback-test.xml
  dropwizard-views-mustache/src/test/resources/logback-test.xml
  dropwizard-views/src/test/resources/logback-test.xml
Labels: improvement

#5748 Use Byte Buddy instead of Javassist in UnitOfWorkAwareProxyFactory
  dropwizard-hibernate/pom.xml
  dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkAwareProxyFactory.java
Labels: task
