Repository dropwizard/dropwizard, pull requests merged in 2022-03, with the labels that each got.

#4836 Ignore code coverage metrics for dropwizard-benchmarks
  dropwizard-benchmarks/pom.xml
Labels: task

#4830 Add default methods to dropwizard-lifecycle's `Managed` interface
  docs/source/manual/core.rst
  dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java
  dropwizard-client/src/main/java/io/dropwizard/client/JerseyClientBuilder.java
  dropwizard-health/src/main/java/io/dropwizard/health/HealthCheckConfigValidator.java
  dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/AutoCloseableManager.java
  dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/ExecutorServiceManager.java
  dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/Managed.java
Labels: improvement

#2926 Add automatic module names for all Dropwizard modules
  dropwizard-assets/pom.xml
  dropwizard-auth/pom.xml
  dropwizard-client/pom.xml
  dropwizard-configuration/pom.xml
  dropwizard-core/pom.xml
  dropwizard-db/pom.xml
  dropwizard-forms/pom.xml
  dropwizard-health/pom.xml
  dropwizard-hibernate/pom.xml
  dropwizard-http2/pom.xml
  dropwizard-jackson/pom.xml
  dropwizard-jdbi3/pom.xml
  dropwizard-jersey/pom.xml
  dropwizard-jetty/pom.xml
  dropwizard-json-logging/pom.xml
  dropwizard-lifecycle/pom.xml
  dropwizard-logging/pom.xml
  dropwizard-metrics-graphite/pom.xml
  dropwizard-metrics/pom.xml
  dropwizard-migrations/pom.xml
  dropwizard-parent/pom.xml
  dropwizard-request-logging/pom.xml
  dropwizard-servlets/pom.xml
  dropwizard-testing/pom.xml
  dropwizard-util/pom.xml
  dropwizard-validation/pom.xml
  dropwizard-views-freemarker/pom.xml
  dropwizard-views-mustache/pom.xml
  dropwizard-views/pom.xml
Labels: task

#4890 Deprecate `FixtureHelpers`
  docs/source/manual/testing.rst
  dropwizard-example/src/test/java/com/example/helloworld/core/PersonTest.java
  dropwizard-example/src/test/java/com/example/helloworld/resources/PeopleResourceTest.java
  dropwizard-example/src/test/java/com/example/helloworld/resources/PersonResourceTest.java
  dropwizard-example/src/test/resources/person.json
  dropwizard-testing/src/main/java/io/dropwizard/testing/FixtureHelpers.java
Labels: task

#4915 Remove dropwizard-util `Optionals`
  dropwizard-util/pom.xml
  dropwizard-util/src/main/java/io/dropwizard/util/Optionals.java
  dropwizard-util/src/test/java/io/dropwizard/util/OptionalsTest.java
Labels: task

#4918 Deprecate Bytestreams and Maps
  dropwizard-util/src/main/java/io/dropwizard/util/ByteStreams.java
  dropwizard-util/src/main/java/io/dropwizard/util/Maps.java
Labels: task

#4916 Remove deprecated parts of dropwizard-util
  dropwizard-configuration/src/main/java/io/dropwizard/configuration/SubstitutingSourceProvider.java
  dropwizard-configuration/src/test/java/io/dropwizard/configuration/UrlConfigurationSourceProviderTest.java
  dropwizard-core/src/test/java/io/dropwizard/server/DefaultServerFactoryTest.java
  dropwizard-core/src/test/java/io/dropwizard/server/SimpleServerFactoryTest.java
  dropwizard-e2e/src/test/java/com/example/sslreload/SslReloadAppTest.java
  dropwizard-health/src/test/java/io/dropwizard/health/response/JsonHealthResponseProviderTest.java
  dropwizard-jdbi3/src/test/java/io/dropwizard/jdbi3/JdbiTest.java
  dropwizard-jetty/src/test/java/io/dropwizard/jetty/GzipHandlerTest.java
  dropwizard-servlets/src/main/java/io/dropwizard/servlets/assets/AssetServlet.java
  dropwizard-servlets/src/main/java/io/dropwizard/servlets/tasks/TaskServlet.java
  dropwizard-testing/src/main/java/io/dropwizard/testing/FixtureHelpers.java
  dropwizard-util/src/main/java/io/dropwizard/util/ByteStreams.java
  dropwizard-util/src/main/java/io/dropwizard/util/CharStreams.java
  dropwizard-util/src/main/java/io/dropwizard/util/DataSize.java
  dropwizard-util/src/main/java/io/dropwizard/util/Lists.java
  dropwizard-util/src/main/java/io/dropwizard/util/Resources.java
  dropwizard-util/src/main/java/io/dropwizard/util/Strings.java
  dropwizard-util/src/main/java/io/dropwizard/util/Throwables.java
  dropwizard-util/src/test/java/io/dropwizard/util/ByteStreamsTest.java
  dropwizard-util/src/test/java/io/dropwizard/util/CharStreamsTest.java
  dropwizard-util/src/test/java/io/dropwizard/util/DataSizeTest.java
  dropwizard-util/src/test/java/io/dropwizard/util/StringsTest.java
Labels: task

#4955 Remove deprecated `FixtureHelpers` from the docs
  docs/source/manual/testing.rst
  dropwizard-example/src/test/java/com/example/helloworld/core/PersonTest.java
Labels: documentation

#4965 Update h2 to 2.1.210
  dropwizard-dependencies/pom.xml
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbDumpCommandTest.java
  dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbStatusCommandTest.java
  dropwizard-migrations/src/test/resources/test-db.mv.db
Labels: dependencies, java

#4979 Update `Optionals` usage for recent Java
  dropwizard-auth/src/main/java/io/dropwizard/auth/AuthFilter.java
  dropwizard-auth/src/main/java/io/dropwizard/auth/CachingAuthenticator.java
  dropwizard-configuration/src/main/java/io/dropwizard/configuration/ConfigurationMetadata.java
  dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/SubResourcesTest.java
  dropwizard-servlets/src/main/java/io/dropwizard/servlets/tasks/TaskServlet.java
  dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/LogbackExcludedTest.java
Labels: improvement

#4978 Remove commons-lang3 as a dependency
  dropwizard-dependencies/pom.xml
  dropwizard-e2e/pom.xml
  dropwizard-e2e/src/main/java/com/example/app1/App1.java
  dropwizard-jetty/pom.xml
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/ZipExceptionHandlingGzipHandler.java
  dropwizard-util/src/main/java/io/dropwizard/util/Throwables.java
  dropwizard-util/src/test/java/io/dropwizard/util/ThrowablesTest.java
  dropwizard-views/pom.xml
  dropwizard-views/src/main/java/io/dropwizard/views/ViewRenderExceptionMapper.java
Labels: improvement

#5019 Remove deprecated `BooleanParam`
  dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/BooleanParam.java
  dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/BooleanParamTest.java
Labels: task

#5045 Remove deprecated `Throwables#getRootCause(Throwable)`
  dropwizard-util/src/main/java/io/dropwizard/util/Throwables.java
Labels: task

#5050 Remove guava as a dependency of dropwizard-auth
  dropwizard-auth/pom.xml
  dropwizard-auth/src/main/java/io/dropwizard/auth/CachingAuthorizer.java
Labels: task

#5051 Remove guava from dropwizard-health
  dropwizard-health/pom.xml
  dropwizard-health/src/main/java/io/dropwizard/health/DefaultHealthFactory.java
Labels: improvement
