Repository dropwizard/dropwizard, pull requests merged in 2023-10, with the labels that each got.

#7617 Restrict execution of the scacap/action-surefire-report
  .github/workflows/maven.yml
Labels: github_actions

#7619 Don't run scacap/action-surefire-report in forks
  .github/workflows/maven.yml
Labels: github_actions

#7618 Don't run scacap/action-surefire-report in forks
  .github/workflows/maven.yml
Labels: github_actions

#7637 Clean test db
  dropwizard-migrations/pom.xml
Labels: bug

#7613 Fix the broken link to Apache HttpClient 5.X migration guide
  docs/source/manual/upgrade-notes/upgrade-notes-3_0_x.rst
Labels: documentation

#7639 Fix maven workflow
  .github/workflows/maven.yml
Labels: github_actions

#7629 Ensure lexicographical order in messages from HealthCheckConfigValidator
  dropwizard-health/src/main/java/io/dropwizard/health/HealthCheckConfigValidator.java
  dropwizard-health/src/test/java/io/dropwizard/health/HealthCheckConfigValidatorTest.java
Labels: improvement

#7653 Ensure lexicographical order in messages from HealthCheckConfigValidator
  dropwizard-health/src/main/java/io/dropwizard/health/HealthCheckConfigValidator.java
  dropwizard-health/src/test/java/io/dropwizard/health/HealthCheckConfigValidatorTest.java
Labels: improvement

#7654 Ensure lexicographical order in messages from HealthCheckConfigValidator
  dropwizard-health/src/main/java/io/dropwizard/health/HealthCheckConfigValidator.java
  dropwizard-health/src/test/java/io/dropwizard/health/HealthCheckConfigValidatorTest.java
Labels: improvement

#7100 Add Codespaces/devcontainer support
  .devcontainer/devcontainer.json
Labels: task

#7688 Add Codespaces/devcontainer support
  .devcontainer/devcontainer.json
Labels: task

#7687 Expose uri compliance
  docs/source/manual/configuration.rst
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpConnectorFactory.java
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/StringMethodDeserializer.java
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/StringMethodSerializer.java
  dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpConnectorFactoryTest.java
  dropwizard-jetty/src/test/resources/yaml/http-connector.yml
Labels: improvement

#7691 Expose uri compliance
  docs/source/manual/configuration.rst
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpConnectorFactory.java
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/StringMethodDeserializer.java
  dropwizard-jetty/src/main/java/io/dropwizard/jetty/StringMethodSerializer.java
  dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpConnectorFactoryTest.java
  dropwizard-jetty/src/test/resources/yaml/http-connector.yml
Labels: improvement

#7537 Request log remote user
  dropwizard-auth/pom.xml
  dropwizard-auth/src/main/java/io/dropwizard/auth/AuthFilter.java
  dropwizard-auth/src/main/java/io/dropwizard/auth/JettyAuthenticationUtil.java
  dropwizard-e2e/pom.xml
  dropwizard-e2e/src/test/java/com/example/request_log/AbstractRequestLogPatternIntegrationTest.java
  dropwizard-e2e/src/test/java/com/example/request_log/RequestLogPatternIntegrationTest.java
Labels: improvement

#7693 Request log remote user
  dropwizard-auth/pom.xml
  dropwizard-auth/src/main/java/io/dropwizard/auth/AuthFilter.java
  dropwizard-auth/src/main/java/io/dropwizard/auth/JettyAuthenticationUtil.java
  dropwizard-e2e/pom.xml
  dropwizard-e2e/src/test/java/com/example/request_log/AbstractRequestLogPatternIntegrationTest.java
  dropwizard-e2e/src/test/java/com/example/request_log/RequestLogPatternIntegrationTest.java
Labels: improvement

#7692 Add jreleaser to simplify release announcements
  .github/workflows/trigger-release.yml
  .gitignore
  .jreleaser/announcement.tpl
  jreleaser.yml
Labels: github_actions

#7742 Add JReleaser to simplify release announcements
  .github/workflows/trigger-release.yml
  .gitignore
  .jreleaser/announcement.tpl
  jreleaser.yml
Labels: github_actions

#7457 Enable support for project loom for Jetty's thread pool
  docs/source/manual/configuration.rst
  dropwizard-core/src/main/java/io/dropwizard/core/server/AbstractServerFactory.java
  dropwizard-core/src/main/java/io/dropwizard/core/server/DefaultServerFactory.java
  dropwizard-core/src/test/java/io/dropwizard/core/VirtualThreadsTest.java
Labels: feature

#7746 Enable support for project loom for Jetty's thread pool
  docs/source/manual/configuration.rst
  dropwizard-core/src/main/java/io/dropwizard/core/server/AbstractServerFactory.java
  dropwizard-core/src/main/java/io/dropwizard/core/server/DefaultServerFactory.java
  dropwizard-core/src/test/java/io/dropwizard/core/VirtualThreadsTest.java
Labels: feature

#7747 Fix token permissions 3.0.x
  .github/workflows/maven.yml
Labels: github_actions

#7748 Fix the broken link to Apache HttpClient 5.X migration guide
  docs/source/manual/upgrade-notes/upgrade-notes-3_0_x.rst
Labels: documentation

#7749 Add JReleaser to simplify release announcements
  .github/workflows/trigger-release.yml
  .gitignore
  .jreleaser/announcement.tpl
  jreleaser.yml
Labels: github_actions

#7760 Use github context to retrieve actor
  .github/workflows/trigger-release.yml
Labels: github_actions

#7761 Use github context to retrieve actor
  .github/workflows/trigger-release.yml
Labels: github_actions
