Repository dropwizard/dropwizard, pull requests merged in 2023-12, with the labels that each got.

#7965 Logback request log: combine headers
  dropwizard-request-logging/src/main/java/io/dropwizard/request/logging/DropwizardJettyServerAdapter.java
  dropwizard-request-logging/src/test/java/io/dropwizard/request/logging/LogbackAccessRequestLogTest.java
Labels: bug

#8008 Logback request log: combine headers
  dropwizard-request-logging/src/main/java/io/dropwizard/request/logging/DropwizardJettyServerAdapter.java
  dropwizard-request-logging/src/main/java/io/dropwizard/request/logging/LogbackAccessRequestLog.java
  dropwizard-request-logging/src/test/java/io/dropwizard/request/logging/LogbackAccessRequestLogTest.java
Labels: improvement

#8014 only create the requestLog once to speed up the test
  dropwizard-request-logging/src/test/java/io/dropwizard/request/logging/old/LogbackClassicRequestLogFactoryTest.java
Labels: improvement

#8050 Fix CodeQL workflow
  .github/workflows/codeql-analysis.yml
Labels: bug, github_actions

#8061 Add deprecation notices
  dropwizard-core/src/main/java/io/dropwizard/core/server/AbstractServerFactory.java
Labels: documentation

#8060 Add GracefulHandler for a graceful shutdown
  dropwizard-core/src/main/java/io/dropwizard/core/server/AbstractServerFactory.java
  dropwizard-core/src/main/java/io/dropwizard/core/server/DefaultServerFactory.java
  dropwizard-core/src/main/java/io/dropwizard/core/server/SimpleServerFactory.java
Labels: improvement

#8093 extra info for enableOCSP and enableCRLDP
  docs/source/manual/configuration.rst
Labels: documentation
