Repository dropwizard/dropwizard, pull requests merged in 2023-09, with the labels that each got.

#7526 Use BouncyCastle for Java 8 and later
  dropwizard-client/pom.xml
  dropwizard-dependencies/pom.xml
Labels: dependencies

#7527 Use BouncyCastle for Java 8 and later
  dropwizard-client/pom.xml
  dropwizard-dependencies/pom.xml
Labels: dependencies

#7528 Use BouncyCastle for Java 8 and later
  dropwizard-client/pom.xml
  dropwizard-dependencies/pom.xml
Labels: dependencies

#7542 Build with Java 21
  .github/workflows/maven.yml
Labels: dependencies, java

#7543 Build with Java 21
  .github/workflows/maven.yml
Labels: dependencies, java

#7544 Build with Java 21
  .github/workflows/maven.yml
  .github/workflows/trigger-release.yml
Labels: dependencies, java

#7027 Issue#7026: ConnectionKeepAliveStrategy didn't use a keepAlive value from HttpClientConfiguration
  dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java
  dropwizard-client/src/test/java/io/dropwizard/client/HttpClientBuilderTest.java
Labels: bug

#7567 ConnectionKeepAliveStrategy should use keepAlive value from HttpClientConfiguration
  dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java
  dropwizard-client/src/test/java/io/dropwizard/client/HttpClientBuilderTest.java
Labels: bug

#7532 Fix NullPointerException in DropwizardApacheConnector
  dropwizard-client/src/main/java/io/dropwizard/client/DropwizardApacheConnector.java
Labels: bug

#7575 Fix NullPointerException in DropwizardApacheConnector
  dropwizard-client/src/main/java/io/dropwizard/client/DropwizardApacheConnector.java
Labels: bug

#7572 Move Dropwizard Archetypes into their own repository
  dropwizard-archetypes/README.md
  dropwizard-archetypes/java-simple/pom.xml
  dropwizard-archetypes/java-simple/src/main/resources/META-INF/maven/archetype-metadata.xml
  dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/README.md
  dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/config.yml
  dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/pom.xml
  dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/src/main/java/__name__Application.java
  dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/src/main/java/__name__Configuration.java
  dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/src/main/resources/banner.txt
  dropwizard-archetypes/java-simple/src/test/resources/projects/ordinary/test.properties
  dropwizard-archetypes/java-simple/src/test/resources/projects/shaded/test.properties
  dropwizard-archetypes/pom.xml
  dropwizard-archetypes/src/main/resources/dropwizard-create
  dropwizard-archetypes/src/test/resources/settings.xml
  pom.xml
Labels: task, dependencies

#7574 Move Dropwizard Archetypes into their own repository
  dropwizard-archetypes/README.md
  dropwizard-archetypes/java-simple/pom.xml
  dropwizard-archetypes/java-simple/src/main/resources/META-INF/maven/archetype-metadata.xml
  dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/README.md
  dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/config.yml
  dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/pom.xml
  dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/src/main/java/__name__Application.java
  dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/src/main/java/__name__Configuration.java
  dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/src/main/resources/banner.txt
  dropwizard-archetypes/java-simple/src/test/resources/projects/ordinary/test.properties
  dropwizard-archetypes/java-simple/src/test/resources/projects/shaded/test.properties
  dropwizard-archetypes/pom.xml
  dropwizard-archetypes/src/main/resources/dropwizard-create
  dropwizard-archetypes/src/test/resources/settings.xml
  pom.xml
Labels: task, dependencies

#7586 Fix token permissions for PRs from forks
  .github/workflows/maven.yml
Labels: github_actions
