Repository dropwizard/dropwizard, pull requests merged in 2023-03, with the labels that each got.

#6767 Properly declare plugin versions in java-simple archetype
  dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/pom.xml
Labels: bug, dependencies

#6769 Properly declare plugin versions in java-simple archetype
  dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/pom.xml
Labels: bug, dependencies

#6768 Properly declare plugin versions in java-simple archetype
  dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/pom.xml
Labels: bug, dependencies

#6789 Revert "Update scacap/action-surefire-report digest to 01b2782"
  .github/workflows/maven.yml
Labels: dependencies, github_actions

#6867 Use Mockito BOM in dropwizard-dependencies
  dropwizard-dependencies/pom.xml
Labels: improvement, dependencies, java

#6868 Use Mockito BOM in dropwizard-dependencies
  dropwizard-dependencies/pom.xml
Labels: improvement, dependencies, java

#6866 Use Mockito BOM in dropwizard-dependencies
  dropwizard-dependencies/pom.xml
Labels: improvement, dependencies, java

#6907 Set application state healthy if there are no unhealthy critical checks
  dropwizard-health/src/main/java/io/dropwizard/health/HealthCheckManager.java
  dropwizard-health/src/test/java/io/dropwizard/health/HealthCheckManagerTest.java
Labels: bug

#6909 Set application state healthy if there are no unhealthy critical checks
  dropwizard-health/src/main/java/io/dropwizard/health/HealthCheckManager.java
  dropwizard-health/src/test/java/io/dropwizard/health/HealthCheckManagerTest.java
Labels: bug

#6916 Fix mustache docs link in views.rst
  docs/source/manual/views.rst
Labels: documentation
