Repository dropwizard/dropwizard, pull requests merged in 2023-02, with the labels that each got.

#6621 Switch back to subclass mock maker in `dropwizard-servlets`
  dropwizard-dependencies/pom.xml
  dropwizard-servlets/pom.xml
Labels: task

#6669 4.0.x Timestamp field comes first in generated JSON log output
  dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/layout/MapBuilder.java
  dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/LayoutIntegrationTests.java
  dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/layout/MapBuilderTest.java
Labels: improvement

#6668 3.0.x Timestamp field comes first in generated JSON log output
  dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/layout/MapBuilder.java
  dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/LayoutIntegrationTests.java
  dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/layout/MapBuilderTest.java
Labels: improvement

#6724 Support setting base branch in release trigger workflow
  .github/workflows/trigger-release.yml
Labels: github_actions

#6721 Fail build at end in Java CI
  .github/workflows/maven.yml
Labels: github_actions

#6692 Add configurable response code meters
  docs/source/manual/configuration.rst
  dropwizard-core/pom.xml
  dropwizard-core/src/main/java/io/dropwizard/server/AbstractServerFactory.java
  dropwizard-core/src/test/java/io/dropwizard/server/AbstractServerFactoryTest.java
  dropwizard-core/src/test/java/io/dropwizard/server/DefaultServerFactoryTest.java
  dropwizard-core/src/test/resources/yaml/server.yml
Labels: feature

#6728 Add configurable response code meters
  docs/source/manual/configuration.rst
  dropwizard-core/pom.xml
  dropwizard-core/src/main/java/io/dropwizard/core/server/AbstractServerFactory.java
  dropwizard-core/src/test/java/io/dropwizard/core/server/AbstractServerFactoryTest.java
  dropwizard-core/src/test/java/io/dropwizard/core/server/DefaultServerFactoryTest.java
  dropwizard-core/src/test/resources/yaml/server.yml
Labels: feature

#6729 Add configurable response code meters
  docs/source/manual/configuration.rst
  dropwizard-core/pom.xml
  dropwizard-core/src/main/java/io/dropwizard/core/server/AbstractServerFactory.java
  dropwizard-core/src/test/java/io/dropwizard/core/server/AbstractServerFactoryTest.java
  dropwizard-core/src/test/java/io/dropwizard/core/server/DefaultServerFactoryTest.java
  dropwizard-core/src/test/resources/yaml/server.yml
Labels: feature
