Repository dropwizard/dropwizard, pull requests merged in 2024-08, with the labels that each got.

#8732 Update package name to correct path in 3.0 docs
  docs/source/manual/upgrade-notes/upgrade-notes-3_0_x.rst
Labels: bug, documentation

#9184 Update package name to correct path in 3.0 docs
  docs/source/manual/upgrade-notes/upgrade-notes-3_0_x.rst
Labels: bug, documentation

#9183 Update package name to correct path in 3.0 docs
  docs/source/manual/upgrade-notes/upgrade-notes-3_0_x.rst
Labels: bug, documentation

#9238 Group Maven plugin updates in Renovate
  renovate.json
Labels: dependencies

#9257 Use the SLF4J BOM to Manage SLF4J Versions
  dropwizard-dependencies/pom.xml
Labels: dependencies, java

#9261 Use SLF4J BOM to manage SLF4J versions
  dropwizard-dependencies/pom.xml
Labels: dependencies, java

#9260 Use SLF4J BOM to manage SLF4J versions
  dropwizard-dependencies/pom.xml
Labels: dependencies, java
