Repository dropwizard/dropwizard, pull requests merged in 2025-08, with the labels that each got.

#10284 Skip Http2WithConscryptTest on ARM MacOS
  dropwizard-http2/src/test/java/io/dropwizard/http2/Http2WithConscryptTest.java
Labels: improvement

#10253 CONTRIBUTING.md: remove Google Group instructions
  CONTRIBUTING.md
Labels: documentation

#10372 Skip Http2WithConscryptTest on ARM MacOS
  dropwizard-http2/src/test/java/io/dropwizard/http2/Http2WithConscryptTest.java
Labels: improvement

#10374 CONTRIBUTING.md: remove Google Group instructions
  CONTRIBUTING.md
Labels: documentation

#10424 ci: update link to Mastodon (foojay.social)
  docs/source/index.rst
  jreleaser.yml
Labels: documentation, github_actions

#10421 docs: fix incorrect format string in archivedLogFilenamePattern
  docs/source/manual/configuration.rst
Labels: documentation
